### ISSUE TITLE
Velociraptors flock from a baby T-Rex

### ISSUE THREAD

**Issue by TheLastBlockbender** [JurassiCraftTeam/JurassiCraft2#114]
I don't really know if this is supposed to happen, but it seems kind of weird to me that when I spawn in a baby T-Rex in a pen of tamed velociraptors, they are all attempting to flock. I think this is pretty unrealistic, and don't know if this is supposed to happen, but I thought I'd post this anyways just in case:)

**Comment by gegy1000** [comment]
You mean they are flocking / running away from it?

**Comment by TheLastBlockbender** [comment]
Yes

**Comment by TheLastBlockbender** [comment]
Even when the velociraptors are adults

**Comment by gegy1000** [comment]
This is situational, if they have low health, they may run.
