### ISSUE TITLE
Dinos don't play drinking animation JurassiCraft 2.0.5 1.10.2

### ISSUE THREAD

**Issue by crakiMDH** [JurassiCraftTeam/JurassiCraft2#117]
This happened with a Gallimimus. Her drinking bar is full, but I've NEVER seen her play the drinking animation. And I saw her run up to the water but no animation played. I haven't seen animations from Triceratops, Parasaurolophus, Dilophosaurus, and Velociraptor. Note that they were all females due to me being lazy on changing some to male. Later when I can I'll test it out with males as well. Tyrannosaurus and Brachiosaurus haven't been tested with either gender yet. FYI, all 5 of the ones that I don't see drinking animations from were tamed. Hope this helps.

**Comment by gegy1000** [comment]
Gender shouldn't have any effect on this, interesting...

**Comment by gegy1000** [comment]
Should be fixed in 2.1.
