### ISSUE TITLE
Dinosaurs (or at least Gallimimus) eat from feeders they can't reach... Or at least try to.

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#118]
![2017-01-09_20 45 14](https://cloud.githubusercontent.com/assets/16602481/21855842/ce6d9dd2-d7ed-11e6-9e0c-3601aeecfce2.png)

As you can see in the picture, there are 5 paddocks used to test how to take care of dinos with DinoMetabolism set to true. The iron blocks show where feeders are (or were if I moved them). Look at the picture, you can see that there are 3 iron blocks in the Triceratops Paddock. Now in the Gallimimus Paddock, there is a feeder that is extremely close to the Gallimimus Paddock. Well, she ran to the feeder and opened it, but because of the iron bars, she was unable to eat the food. Dinosaurs should only be able to eat from feeders that are within their reach. Hope this long explanation is understandable.

(P.S the feeder is in the lower left corner in the Triceratops Paddock. Hope you can know which one I'm talking about.)

**Comment by gegy1000** [comment]
Do you mean the Gallimimus went to the feeder in the Triceratops paddock?

**Comment by gegy1000** [comment]
This is interesting, I did add a check in 2.0.4 to ensure that the feeder could be reached.

**Comment by crakiMDH** [comment]
I'd like to add in that I've seen this happen with water.
Perhaps the check was accidentally removed in 2.0.5.

**Comment by Cazsius** [comment]
Old issue, waiting for someone else to see or else cannot be reproduced.
