### ISSUE TITLE
LangHelper performance

### ISSUE THREAD

**Issue by gegy1000** [JurassiCraftTeam/JurassiCraft2#120]
Replace LangHelper usages with formatted translation via `I18n.translateToLocalFormatted`

**Comment by twoninefour** [comment]
Isn't `I18n.translateToLocalFormatted` deprecated now?

**Comment by gegy1000** [comment]
It's deprecated by Mojang, this means nothing for modders.

**Comment by Leppan** [comment]
Isn't that supposed to be used on serverside? And then a different I18n.format("") is used on clientside?
