### ISSUE TITLE
Dinosaurs glitch through walls

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#124]
This is a fairly common thing. If a diagonal wall is made and a dinosaur is right against it when the chunk is unloaded, they have a high chance to either suffocate in the walls or, in the worst cases, glitch through it and roam freely at their will. I've seen this happen with Dilophosaurus, Triceratops, Parasaurolophus, and Gallimimus. Although it's not impossible for this to happen with Tyrannosaurus, Velociraptor and Brachiosaurus. Brachios are too slow of flockers to get close to the walls, while I haven't had Paddocks build for Rex or Raptors, so I can't confirm. This is most often happening when they're flocking.

**Comment by Gamebrothers4** [comment]
Has this been fixed?
