### ISSUE TITLE
Superlag/World Freeze Problem

### ISSUE THREAD

**Issue by kenijey** [JurassiCraftTeam/JurassiCraft2#127]
I tried many things, it is happening only this mod is installed. **Breaking a block, trying to eat something, hitting mobs, are lagged about 5-6 seconds.** I set dinosaurs spawn enabled. Using forge 2226, latest Jurassicraft. Please help. Thanks.
Note: I did never get a crash, but my world is very slow loading, and extremely lagging sometimes/some world creatings or some places on world. It looks like there is an infinite loop in the code.

**Comment by gegy1000** [comment]
What version of the mod are you using? 2.0.5 introduced some large performance optimizations. Could you run a profiler such as VisualVM and share the results?

**Comment by kenijey** [comment]
using minecraft 1.11.2, Jurassicraft 2.0.5, forge 2226. how can i do that? visualvm, what is this and how can i setup it? thanks.

**Comment by gegy1000** [comment]
@twoninefour Has come up with an optimization that should greatly reduce this for 2.1. However, it'd be best that we profile more before release.
