### ISSUE TITLE
Game freezes when spawning T-rex

### ISSUE THREAD

**Issue by La-La-La-Labia** [JurassiCraftTeam/JurassiCraft2#136]
When i spawn one the game freezes the sound of the trex is still on but only see its shadow and the game freezes

**Comment by Alex-the-666** [comment]
Probably because the texture is large

possible fix to this would be a config to decrease the texture size for poopy PCs like mine.

**Comment by La-La-La-Labia** [comment]
what do you mean?

**Comment by gegy1000** [comment]
The texture size is reduced in 2.1
