### ISSUE TITLE
Velociraptors have incomplete skeletons

### ISSUE THREAD

**Issue by crakiMDH** [JurassiCraftTeam/JurassiCraft2#141]
When a Velociraptor is killed and the carcass fully rots away, only the skull, teeth, and the talon claw drop out of the whole skeleton. On top of this, I can't seem to find the rest of the skeleton of the raptor in creative inventories either.

**Comment by gegy1000** [comment]
But if they don't exist, should they be expected to drop?

**Comment by gegy1000** [comment]
All bones added in 2.1
