### ISSUE TITLE
[1.10.2] Random server crash possibly involving feeder

### ISSUE THREAD

**Issue by Thedrummonger** [JurassiCraftTeam/JurassiCraft2#145]
I have experienced the same server crash involving JurassiCraft multiple times now. the crash seems to have something to do with the feeder block. Here are two of the crash reports I've received. 

https://pastebin.com/pecuvyxh

https://pastebin.com/h3CvpMiH

**Comment by gegy1000** [comment]
This is already fixed for the next version. Thanks for the report, anyway. =)

**Comment by Alex-the-666** [comment]
Thank you for your report. Even though the said issue has been contained, resolved, then systematically removed, it still brings pleasure to our demeaning lives. Thank you again. ❤️
