### ISSUE TITLE
Mural VC spawning

### ISSUE THREAD

**Issue by gegy1000** [JurassiCraftTeam/JurassiCraft2#154]
Murals spawn incorrectly in most cases within the VC generation.

**Comment by gegy1000** [comment]
I'm not sure why this is happening, it'd be good to test if this occurs with the default structure rotation. My first guess would be that this is caused by the rotation of the entities when they are being spawned. Due to them being so large, it's possible they are rotating around the wrong point.

**Comment by JCHyperion** [comment]
It was already tested and we concluded it was because of the rotations.
In a normally rotated vc, this doesn't happen.

**Comment by gegy1000** [comment]
The rotation of murals is handled by `EntityHanging`. It could be that at fault, or it could be the area validation and fit inside `MuralEntity` creating the wrong result.

**Comment by Gamebrothers4** [comment]
Temporary removed the rotation i can't find the cause of this

**Comment by Gamebrothers4** [comment]
ups
