### ISSUE TITLE
Tour Vehicle Rewrite

### ISSUE THREAD

**Issue by gegy1000** [JurassiCraftTeam/JurassiCraft2#155]
The Tour Vehicle requires a rewrite. The minecart base code doesn't do all that is needed for this.

**Comment by pau101** [comment]
Needs state syncing so it is ridaeble when on rail.

**Comment by Wyn-Price** [comment]
This should be done in the latest commit. [d1bc13c](https://github.com/JurassiCraftTeam/JurassiCraft2/commit/d1bc13c67df0d5959e5cb91750f0c93844f26243). If you want any changes or anything i change stuff around.

**Comment by Cazsius** [comment]
Finished by Wyn.
