### ISSUE TITLE
Visitor Center Loot Issues

### ISSUE THREAD

**Issue by gegy1000** [JurassiCraftTeam/JurassiCraft2#165]
Not confirmed, requires investigation. Apparently sometimes chests appear empty.
Also, journals are not yet implemented as apart of the loot.

**Comment by gegy1000** [comment]
This is likely due to the chests being overfilled. It'd be better for the loot tables to be created manually with JSON instead of in-code, and tune the amount of pools spawned, as was started [here].(https://github.com/JurassiCraftTeam/JurassiCraft2/blob/2.1/src/main/resources/assets/jurassicraft/loot_tables/structure/visitor_centre/ground_storage.json).

**Comment by gegy1000** [comment]
Currently bone spawning has issues, not all dinosaurs have the `tooth` bone type.

**Comment by Gamebrothers4** [comment]
Closed fixed with the new JSON loottables
