### ISSUE TITLE
Mammal Suggestion: Irish Elk

### ISSUE THREAD

**Issue by IrishGitlord1** [JurassiCraftTeam/JurassiCraft2#167]
The Irish Elk, aka Megaloceros giganteus, is an extinct giant deer, the largest deer to ever live. It's not Irish either, so technically it's name is completely false, but I like it anyway. I'd like this to be added along side Megatapirus if at all possible.

**Comment by Flyerthe** [comment]
It's called the Irish Elk because so many of them have been found in Peat Bogs from Ireland.
It would be a cool edition to the game but probably be late-on in the process because they aren't mentioned in the jp books/movies and only in the games.

**Comment by Flyerthe** [comment]
it'll probs be added in the mammel updates
