### ISSUE TITLE
[1.11.2] JurassiCraft 2.0.5 Bug Reports

### ISSUE THREAD

**Issue by iDatHaxDoe** [JurassiCraftTeam/JurassiCraft2#168]
The Cleaning station consumes the water bucket when I put it down;
Also, when I put my Brachiossauros hatched egg down, the dinosaur appears, but I can't do anything with him because it says that I do not own that dinosaur.

**Comment by IrishGitlord1** [comment]
@iDatHaxDoe Brachiosurus can't be tamed, but idk about the cleaning station.

**Comment by gegy1000** [comment]
This is a bug with the 1.11.2 port, and will likely not be fixed unless a port of 2.1 is done.

**Comment by SanAndreasP** [comment]
Cleaning station have been adressed now in https://github.com/JurassiCraftTeam/JurassiCraft2/commit/e9894d30bb63bd351d8596be6e225677f5d27e7d
