### ISSUE TITLE
Modded blocks disappear when updating a world (2.0.5-TB)

### ISSUE THREAD

**Issue by JCHyperion** [JurassiCraftTeam/JurassiCraft2#177]
I've seen some blocks disappear and change, so it's probably an ID bug. I've seen Peat and Moss disappear, and glass turning into peat moss.

**Comment by gegy1000** [comment]
This may be caused to incorrect remapping in the [FMLMissingMappingsEvent](https://github.com/JurassiCraftTeam/JurassiCraft2/blob/2.1/src/main/java/org/jurassicraft/JurassiCraft.java#L83). It'd be good to test without it to see if this still occurs. (Action figures would be an exception, they will have missing mappings as that's what the event deals with)
