### ISSUE TITLE
Crash Server [FeederBlockEntity]

### ISSUE THREAD

**Issue by HeberonYT** [JurassiCraftTeam/JurassiCraft2#178]
Hi.
I was playing on my server and unexpectedly crashed.
The characteristics of my server are:
minecraft 1.10.2
Forge version: 12.18.3.2281
Java version: 1.8.0_111

Here is the report.
https://pastebin.com/raw/N7KJ1cNJ

**Comment by PoetPlays** [comment]
Same issue. Same stack trace. In a couple cases it seems to be that placing "chicken" in the feeder causes the crash... specifically when the dinosaur goes to feed it would seem.

`Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: -1
	at org.jurassicraft.server.block.entity.FeederBlockEntity.func_73660_a(FeederBlockEntity.java:310)

**Comment by gegy1000** [comment]
This is fixed in 2.1.
