### ISSUE TITLE
Cascading Worldgen Lag

### ISSUE THREAD

**Issue by PoetPlays** [JurassiCraftTeam/JurassiCraft2#179]
FML Logs are being flooded with:

> JurassiCraft loaded a new chunk (37, -62  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

This is with 2.0.5 running on 1.10.2.

Apart from this error message flooding in with a different chunk on each line, there doesn't appear to be any other errors I can find related to this.

Might be related to #127

**Comment by PoetPlays** [comment]
Nevermind. See this is a duplicate of #146

**Comment by gegy1000** [comment]
Should be fixed in 2.1, closing.
