### ISSUE TITLE
Microraptor climbing and suffocating

### ISSUE THREAD

**Issue by JCHyperion** [JurassiCraftTeam/JurassiCraft2#182]
Microraptors can currently climb every surface, which should only be wooden logs instead. They also tend to suffocate when trying to climb for unknown reasons.

**Comment by gegy1000** [comment]
They only intentionally climb trees, but if a block gets in their way it will climb it due to the navigation behaviour.

**Comment by JCHyperion** [comment]
Well, even if the logs are covered with a layer of blocks, it still tries to climb it, and bugs out in the process.

**Comment by gegy1000** [comment]
This is likely related to https://github.com/JurassiCraftTeam/JurassiCraft2/blob/2.1/src/main/java/org/jurassicraft/server/entity/ai/RaptorClimbTreeAI.java#L100. `targetX` and `targetZ` may be set incorrectly, causing the microraptor to teleport inside the tree.
