### ISSUE TITLE
Extended Mod Compatibility

### ISSUE THREAD

**Issue by Totemaster** [JurassiCraftTeam/JurassiCraft2#184]
Compatibility
- [ ] Plants should be able to spread to Biomes O Plenty sandy/silty/loamy dirt/grass. They can currently be placed on it and can spread from it, but not to it.
- [ ] Goats (and herbivorous dinosaurs) should be able to recognize plant-based food from the following mods:
	* Biomes O' Plenty
	* Natura
- [ ] JC trees should be affected by Tree Chopper.

Ideas
- [x] Configurable structure spawn rates in the final version?

**Comment by Codyrex78117** [comment]
Some are fixed, some are abandoned because they're not very important

**Comment by gegy1000** [comment]
In that case, should this issue be closed?

**Comment by JCHyperion** [comment]
Not really. We still need to fix those. It's just that we don't need to fix those in the first 2.1 release
