### ISSUE TITLE
Strange Dinosaur Interation

### ISSUE THREAD

**Issue by TheCreeper23** [JurassiCraftTeam/JurassiCraft2#187]
I spawn a herd of Parasaurolophus, then a T. Rex; the T. Rex is uphill from the herd but has a hard time getting down to them fast [I've seen this same problem but worse when going uphill, which the Rexes can barely do].  Once the T. Rex is level with the herd, the Parasaurolophus don't strt running until it's already too late.

**Comment by TheCreeper23** [comment]
Another issue with dinosaur interactions; in a fight, one of the dinosaurs will attack multiple times while the other one does nothing but get knocked back, making the fights very one-sided.

**Comment by TheCreeper23** [comment]
Velociraptors will climb all the way up a wall when walking near them.

**Comment by gegy1000** [comment]
Split up into #194 and #195
