### ISSUE TITLE
Minecraft crash with Jurassicraft 2.1.0

### ISSUE THREAD

**Issue by OfficerGamer** [JurassiCraftTeam/JurassiCraft2#188]
I installed Jurassicraft 2.1.0, but Minecraft still crashes.
[crash-2017-10-01_19.08.27-client.txt](https://github.com/JurassiCraftTeam/JurassiCraft2/files/1347755/crash-2017-10-01_19.08.27-client.txt)

I tried Jurassicraft 2.1.1 and goes to main menu and works on new world, but crashes with older Jurassicraft worlds.
[crash-2017-10-01_19.40.13-client.txt](https://github.com/JurassiCraftTeam/JurassiCraft2/files/1347767/crash-2017-10-01_19.40.13-client.txt)

For some reason, Jurassicraft made the birch tree leaves gray.
![2017-10-01_19 39 32](https://user-images.githubusercontent.com/32444100/31062691-5b92ad02-a6e1-11e7-9de8-272b497aee48.png)

**Comment by gegy1000** [comment]
Completely unrelated to JurassiCraft.

**Comment by OfficerGamer** [comment]
It has to be, because the tree leaves were their normal textures before I installed the newest Jurassicraft.

**Comment by gegy1000** [comment]
Both of these issues only occur when other mods are installed. I suspect one of them is interacting with JC badly.
