### ISSUE TITLE
Dinosaurs get stuck in water

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#189]
Versions 2.1.1:

- [x] Dinosaurs just seem to randomly turn around weirdly, dunno if intended.

- [ ] Some creatures such as Tyrannosaurus and I believe Brachiosaurus get stuck on water once more.

- [x] There doesn't seem to be a way to dismount Microraptor off your shoulder.

- [x] Velociraptors seem to climb like spiders. Bug or intended feature?

- [x] Microraptors don't seem to always climb to glide, but the real thing is that they are hopeless in Dark Oak Trees; they almost always get stuck in them, because Dark Oaks usually have a few blocks out. And the Microraptors don't even try getting off.

- [x] This isn't more of a bug, it's more of a question; is there a way to make the electric fence bases slope up?

**Comment by gegy1000** [comment]
The electric fences can't slope up, although the wires can if the fence bases go up over many blocks.

**Comment by epicslayer999** [comment]
Awesome, thanks for the info.

**Comment by JCHyperion** [comment]
Press "C" to the microraptor off your shoulder. This is a configurable key.

**Comment by gegy1000** [comment]
What do you mean by them turning weirdly?

**Comment by gegy1000** [comment]
> Dinosaurs don't react to anything anymore. Well, barely. They don't flock together, Gallimimus and Parasaurolophus don't flee or react to Tyrannosaurus, etc.. Triceratops do seem to react properly when there's two, but when there's only one it doesn't flee.
Removed from this issue, moved over to #195
