### ISSUE TITLE
Dinosaurs travel badly along hills

### ISSUE THREAD

**Issue by gegy1000** [JurassiCraftTeam/JurassiCraft2#194]
From #187:
> I spawn a herd of Parasaurolophus, then a T. Rex; the T. Rex is uphill from the herd but has a hard time getting down to them fast [I've seen this same problem but worse when going uphill, which the Rexes can barely do].

**Comment by gegy1000** [comment]
Why was this closed?

**Comment by Gamebrothers4** [comment]
Ive changed something and after that i really did not see this issue accurign anymore
