### ISSUE TITLE
Game crash when loading old world

### ISSUE THREAD

**Issue by OfficerGamer** [JurassiCraftTeam/JurassiCraft2#202]
I tried Jurassicraft version 2.1.2 and I had Llibrary 1.7.7 and I tried loading an old world which had Jurassicraft version 2.0.5 and it crashed the game.

Here is the crash file:
[crash-2017-10-05_21.27.32-client.txt](https://github.com/JurassiCraftTeam/JurassiCraft2/files/1361534/crash-2017-10-05_21.27.32-client.txt)

**Comment by Gamebrothers4** [comment]
This not JC Its an other mod
