### ISSUE TITLE
Dinosaurs don't retaliate when attacked

### ISSUE THREAD

**Issue by NoahNinja** [JurassiCraftTeam/JurassiCraft2#203]
In the newest version, I spawned in two raptors and a t-Rex, the Rex bit on of the raptors, the raptor just sat there and did nothing, the other raptor attacks the t-Rex, but the Rex doesn't do anything about it, there seems to be some sort of delay in their reaction time, I punched a triceratops, it took it about 5 seconds to start chasing me

**Comment by SanAndreasP** [comment]
has been fixed with recent AI improvements
