### ISSUE TITLE
Skeleton Assembly Table Crashes Users on Servers

### ISSUE THREAD

**Issue by Tux12411** [JurassiCraftTeam/JurassiCraft2#204]
On the Official JurassiCraft Server owned by the DragonPeas. I noticed that when using the Skeleton Assembly Table it freezes up the game and crashes the player, not the server. 
"The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen" This is the latest version of the mod (2.1.2) so I hope this can get fixed fairly soon!

**Comment by gegy1000** [comment]
Could you send the full crash report? Can't do much with just that.

**Comment by Tux12411** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.7-1.10.2.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 10/8/17 10:34 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at de.eydamos.backpack.util.NBTItemStackUtil.hasTag(NBTItemStackUtil.java:28)
	at de.eydamos.backpack.util.NBTItemStackUtil.getString(NBTItemStackUtil.java:52)
	at de.eydamos.backpack.tier.TierLeather.getTierByItemStack(TierLeather.java:47)
	at de.eydamos.backpack.tier.TierLeather.setTier(TierLeather.java:64)
	at de.eydamos.backpack.recipe.RecipeBackpackPieceMiddle.func_77572_b(RecipeBackpackPieceMiddle.java:60)
	at assets.recipehandler.CraftingHandler.getCraftResult(CraftingHandler.java:108)
	at assets.recipehandler.CraftingHandler.getNumberOfCraft(CraftingHandler.java:146)
	at assets.recipehandler.GuiEventHandler$CreativeButton.func_146112_a(GuiEventHandler.java:49)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:71)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:81)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.eydamos.backpack.util.NBTItemStackUtil.hasTag(NBTItemStackUtil.java:28)
	at de.eydamos.backpack.util.NBTItemStackUtil.getString(NBTItemStackUtil.java:52)
	at de.eydamos.backpack.tier.TierLeather.getTierByItemStack(TierLeather.java:47)
	at de.eydamos.backpack.tier.TierLeather.setTier(TierLeather.java:64)
	at de.eydamos.backpack.recipe.RecipeBackpackPieceMiddle.func_77572_b(RecipeBackpackPieceMiddle.java:60)
	at assets.recipehandler.CraftingHandler.getCraftResult(CraftingHandler.java:108)
	at assets.recipehandler.CraftingHandler.getNumberOfCraft(CraftingHandler.java:146)
	at assets.recipehandler.GuiEventHandler$CreativeButton.func_146112_a(GuiEventHandler.java:49)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:71)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:81)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: org.jurassicraft.client.gui.SkeletonAssemblyGui
	Mouse location: Scaled: (341, 186). Absolute: (683, 372)
	Screen size: Scaled: (683, 373). Absolute: (1366, 745). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Tux12411'/35699, l='MpServer', x=1572.89, y=60.45, z=-366.82]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1522,70,646), Chunk: (at 2,4,6 in 95,40; contains blocks 1520,0,640 to 1535,255,655), Region: (2,1; contains chunks 64,32 to 95,63, blocks 1024,0,512 to 1535,255,1023)
	Level time: 11712558 game time, 950913 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Tux12411'/35699, l='MpServer', x=1572.89, y=60.45, z=-366.82]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 483143880 bytes (460 MB) / 2989490176 bytes (2851 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2488 84 mods loaded, 84 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2488.jar) 
	UCHIJAAAAAA	Forge{12.18.3.2488} [Minecraft Forge] (forge-1.10.2-12.18.3.2488.jar) 
	UCHIJAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJAAAAAA	ItemBlacklist{1.2.0.11} [ItemBlacklist] (ItemBlacklist-1.9.4-1.2.0.11.jar) 
	UCHIJAAAAAA	uncraftingTable{1.6.5} [Uncrafting Table] ([1.10.2]UncraftingTable-1.6.5.jar) 
	UCHIJAAAAAA	Ambience{GRADLE:VERSION-GRADLE:BUILD} [Ambience] (Ambience 1.0-6.jar) 
	UCHIJAAAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAAAA	appleskin{1.0.8} [AppleSkin] (AppleSkin-mc1.10.2-1.0.8.jar) 
	UCHIJAAAAAA	backpack{3.0.1} [Backpack] (backpack-3.0.1-1.10.2.jar) 
	UCHIJAAAAAA	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	UCHIJAAAAAA	baublesstuff{3.0.2} [Baubles Stuff] (baublesstuff-3.0.2.jar) 
	UCHIJAAAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCHIJAAAAAA	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCHIJAAAAAA	blockdrops{1.1.1} [Block Drops] (BlockDrops-1.10.2-1.1.1.jar) 
	UCHIJAAAAAA	blocklings{4.1.11} [WillR27's Blocklings] (Blocklings 4.1.11 - 1.10.2.jar) 
	UCHIJAAAAAA	boosterrockets{1.0.2} [BoosterRockets] (BoosterRockets-1.10.2-1.1.0.jar) 
	UCHIJAAAAAA	ctm{MC1.10.2-0.2.3.26} [CTM] (CTM-MC1.10.2-0.2.3.26.jar) 
	UCHIJAAAAAA	chisel{MC1.10.2-0.0.14.33} [Chisel] (Chisel-MC1.10.2-0.0.14.33.jar) 
	UCHIJAAAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJAAAAAA	chiselsandbits{12.16} [Chisels & Bits] (chiselsandbits-12.16.jar) 
	UCHIJAAAAAA	sanlib{1.0.1} [SanAndreasPs Mod Library] (SanLib-1.10.2-1.0.1.jar) 
	UCHIJAAAAAA	claysoldiers{3.0.0-alpha.2} [Clay Soldiers Mod] (ClaySoldiersMod-1.10.2-3.0.0-alpha.2.jar) 
	UCHIJAAAAAA	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJAAAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAAAAAA	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCHIJAAAAAA	cookingforblockheads{4.2.45} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.45.jar) 
	UCHIJAAAAAA	eleccore{1.7.431} [ElecCore] (ElecCore-1.10.2-1.7.431.jar) 
	UCHIJAAAAAA	craftingtableiv{1.0} [CraftingTable-IV] (CraftingTableIV-1.4.113.jar) 
	UCHIJAAAAAA	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCHIJAAAAAA	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.5.jar) 
	UCHIJAAAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.3_1.10.2.jar) 
	UCHIJAAAAAA	props{2.4.3} [Decocraft] (Decocraft-2.4.3_1.10.2.jar) 
	UCHIJAAAAAA	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIJAAAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAAAA	EnderIO{1.10.2-3.1.193} [Ender IO] (EnderIO-1.10.2-3.1.193.jar) 
	UCHIJAAAAAA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCHIJAAAAAA	ExtraBitManipulation{1.10.2-2.5.1} [Extra Bit Manipulation] (ExtraBitManipulation-1.10.2-2.5.1.jar) 
	UCHIJAAAAAA	minefactoryreloaded{2.9.0B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar) 
	UCHIJAAAAAA	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UCHIJAAAAAA	thermalexpansion{5.1.10} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.10.25-universal.jar) 
	UCHIJAAAAAA	zerocore{1.10.2-0.1.1.1} [Zero CORE] (zerocore-1.10.2-0.1.1.1.jar) 
	UCHIJAAAAAA	bigreactors{1.10.2-0.4.5.44} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.44.jar) 
	UCHIJAAAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAAAA	forgemultipartcbe{2.0.0.38} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAAAA	microblockcbe{2.0.0.38} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAAAA	minecraftmultipartcbe{2.0.0.38} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAAAA	Harvest{1.10.2-1.1.0-10} [Harvest] (Harvest-1.10.2-1.1.0-10.jar) 
	UCHIJAAAAAA	InventoryPets{1.4.9.9} [Inventory Pets] (inventorypets-1.10-1.4.9.9.jar) 
	UCHIJAAAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAAAA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.10.2-0.11.0.jar) 
	UCHIJAAAAAA	jehc{1.2.2} [Just Enough HarvestCraft] (jehc-1.10.2-1.2.2.jar) 
	UCHIJAAAAAA	journeymap{1.10.2-5.5.0} [JourneyMap] (journeymap-1.10.2-5.5.0.jar) 
	UCHIJAAAAAA	llibrary{1.7.7} [LLibrary] (llibrary-1.7.7-1.10.2.jar) 
	UCHIJAAAAAA	jurassicraft{2.1.2} [JurassiCraft] (JurassiCraft-2.1.2.jar) 
	UCHIJAAAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAAAA	login_shield{1.10.2-25-g2a63586} [Login Shield] (Login_Shield-1.10.2-25-g2a63586.jar) 
	UCHIJAAAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAAAA	MineFactoryReloaded|CompatVanilla{2.9.0B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar) 
	UCHIJAAAAAA	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.10.2).jar) 
	UCHIJAAAAAA	fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
	UCHIJAAAAAA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJAAAAAA	p455w0rdslib{1.0.30} [p455w0rd's Library] (p455w0rdslib-1.10.2-1.0.30.jar) 
	UCHIJAAAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAAAA	reauth{3.5.0} [ReAuth] (ReAuth-3.5.0.jar) 
	UCHIJAAAAAA	reborncore{2.13.6.142} [RebornCore] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UCHIJAAAAAA	reborncore-mcmultipart{2.13.6.142} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UCHIJAAAAAA	refinedstorage{1.2.26} [Refined Storage] (refinedstorage-1.2.26.jar) 
	UCHIJAAAAAA	rebornstorage{1.0.0} [RebornStorage] (RebornStorage-1.10.2-1.0.3.30.jar) 
	UCHIJAAAAAA	sanplayermodel{1.0.0} [SanAndreasPs Player Model] (SanLib-1.10.2-1.0.1.jar) 
	UCHIJAAAAAA	shulkerdrops{0.3} [Shulker Drops] (ShulkerDrops-0.3.jar) 
	UCHIJAAAAAA	simplyjetpacks{2.1.3.55} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.1.3.55.jar) 
	UCHIJAAAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCHIJAAAAAA	supersoundmuffler{1.0.1.4} [Super Sound Muffler] (supersoundmuffler-1.10.2-1.0.1.4.jar) 
	UCHIJAAAAAA	thermaldynamics{2.0.11} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.11.17-universal.jar) 
	UCHIJAAAAAA	tinkersdefense{1.4.0.8a} [Tinkers' Defense] (tinkersdefense-1.4.0.8a.jar) 
	UCHIJAAAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAAAA	usefulnullifiers{1.3.5} [Useful Nullifiers] (usefulnullifiers-1.3.5.jar) 
	UCHIJAAAAAA	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCHIJAAAAAA	waystones{2.0.13} [Waystones] (Waystones_1.10.2-2.0.13.jar) 
	UCHIJAAAAAA	wcg{1.0.0} [Wireless Crafting Grid] (WirelessCraftingGrid-1.10.2-1.0.0.jar) 
	UCHIJAAAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJAAAAAA	WorldEditCuiFe{1.0.7} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.7-mf-1.10.2-12.18.2.2125.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.7-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics'
	minefactoryreloaded: -[1.10.2]2.9.0B1-226
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * An unsupportted RF API is installed (1.7.0 from (guessing) jar:file:/C:/Users/Pace%20Kids/Documents/Curse/Minecraft/Instances/The%20Official%20Jurassicraft%20Modpack%20-%20DragonPeas%20Network/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/CoFHAPIProps.class).
                    Ender IO needs at least 1.4.0 and will NOT work with older versions.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Pace%20Kids/Documents/Curse/Minecraft/Instances/The%20Official%20Jurassicraft%20Modpack%20-%20DragonPeas%20Network/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Pace%20Kids/Documents/Curse/Minecraft/Instances/The%20Official%20Jurassicraft%20Modpack%20-%20DragonPeas%20Network/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Pace%20Kids/Documents/Curse/Minecraft/Instances/The%20Official%20Jurassicraft%20Modpack%20-%20DragonPeas%20Network/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Pace%20Kids/Documents/Curse/Minecraft/Instances/The%20Official%20Jurassicraft%20Modpack%20-%20DragonPeas%20Network/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Pace%20Kids/Documents/Curse/Minecraft/Instances/The%20Official%20Jurassicraft%20Modpack%20-%20DragonPeas%20Network/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Pace%20Kids/Documents/Curse/Minecraft/Instances/The%20Official%20Jurassicraft%20Modpack%20-%20DragonPeas%20Network/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Pace%20Kids/Documents/Curse/Minecraft/Instances/The%20Official%20Jurassicraft%20Modpack%20-%20DragonPeas%20Network/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Pace%20Kids/Documents/Curse/Minecraft/Instances/The%20Official%20Jurassicraft%20Modpack%20-%20DragonPeas%20Network/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Pace%20Kids/Documents/Curse/Minecraft/Instances/The%20Official%20Jurassicraft%20Modpack%20-%20DragonPeas%20Network/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	EnderStorage Invalid Fingerprint Reports: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.6.142
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-12.18.3.2488
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.4.0 - Build 20.19.15.4549, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.10.2-r4.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU 3825U @ 1.90GHz

**Comment by gegy1000** [comment]
This looks like an issue from the `Backpack` mod, not JurassiCraft.
