### ISSUE TITLE
Dinosaurs don't eat prehistoric plants :c

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#205]
So, I had a lovely lil' female Mussaurus. She was clearly hungry, but did not eat any of the Dicroidium zuberi plants just lying around. However, dinosaurs do seem to eat grass and flowers. Maybe the A.I got mixed up and they're supposed to eat plants but eat vanilla ones instead? Thank you.

**Comment by gegy1000** [comment]
Cannot reproduce: https://streamable.com/0u1of
