### ISSUE TITLE
Gallimimus can leap two blocks.

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#207]
The title says it all. If this is intended, Gallimimus should only leap 2 blocks if they're scared or flocking. Hope it's not a bug, and if it isn't, hope my suggestion is considered. :)

**Comment by epicslayer999** [comment]
No, Gegy, the Gallimimus ALREADY leap two blocks. I'm suggesting them to do so only if they're running while fleeing or flocking.

**Comment by gegy1000** [comment]
I know.

**Comment by Flyerthe** [comment]
galli leap 2 blocks any time they want to go up 1
and take damage in the process
