### ISSUE TITLE
Possible suggestion:

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#210]
So, we all want to have live feeding with goats and T.rexes. Could it be possible for 2.1.3 for Tyrannosaurus and maybe other animals to hunt goats and humans even if the config option for only hunting when hungry is set to true even if they aren't hungry? Thanks!

**Comment by Flyerthe** [comment]
I think the same as you. Rexes should eat creatures even when they aren't hungry, the same with the raptors. Dilo's shouldn't though as they aren't as intelligent.
