### ISSUE TITLE
Mussaurus Drink water out of nowhere.

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#211]
I kind of cruelly kept a Mussaurus in a superflat desert biome, and put her in a butcher villager yard thing with fences. She seemed to have drank water out of no where.

**Comment by Gamebrothers4** [comment]
Wich version is this ❓

**Comment by epicslayer999** [comment]
2.1.2.

**Comment by Gamebrothers4** [comment]
Might be fixed in 2.1.3

**Comment by Cazsius** [comment]
Old issue, not verified, waiting for someone to reopen.
