### ISSUE TITLE
Suggestions (The 3rd one and last one, could be fixed for 2.1.3)

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#213]
Suggestions
- [ ] Gallimimus should have an attacking animation. I proved that they DO attack you, if you attack the babies in the presence of adults.

- [ ] Dilophosaurus need a calling animation. They're the only animal who's smart enough to go in flocks, herds, gangs, packs, or pairs that doesn't have a calling animation.

- [x] The Tyrannosaurus model in versions 2.1 and up has un-even arms. Intended or just a small glitch?

- [ ] Gallimimus could possibly have an animation for when they leap up two blocks.

Bugs
- [x] Microraptors should flee from Tyrannosaurus, not attack and eventually kill them!

- [x] ~~Male and female dinosaurs don't seem to breed very often.~~

**Comment by Gamebrothers4** [comment]
5. They need to build up an relationship first ;P

4. I don't even know why the microraptor attacks the rex

**Comment by BrownBoiiWonder** [comment]
Suggestion #3 is how the model was made(which is something that won't be there with the new model)
