### ISSUE TITLE
2.1.2 issues

### ISSUE THREAD

**Issue by Totemaster** [JurassiCraftTeam/JurassiCraft2#214]
- [x] Cooked Dilo meat has the same texture as raw Dilo meat.
- [x] Dilo skeleton crafting recipe still works, even if not all components are present.
- [x] Coelacanth and Velociraptor skeleton crafting recipes don't work.
- [x] Herbivores seem a little "reluctant" to graze on JC plants. They do it sometimes, but not very often, even when hungry.

**Comment by gegy1000** [comment]
The last one is fixed for 2.1.3 already.
