### ISSUE TITLE
File Download for Release MC 1.7.10 says Jurassicraft 1.4.0

### ISSUE THREAD

**Issue by Physicist1616** [JurassiCraftTeam/JurassiCraft2#217]
I can't tell if I'm downloading 1.4.0 or just a mis-named 1.4.6.

If it's actually 1.4.6 misnamed, oh well.  If it's actually the wrong file version... I'm excited for fixes/features; I know this mod has grown a lot since 1.7.10, but... Witchery and Thaumcraft.

**Comment by gegy1000** [comment]
It's misnamed, sorry about that.
