### ISSUE TITLE
Plants spawn on non-dirt blocks

### ISSUE THREAD

**Issue by BrownBoiiWonder** [JurassiCraftTeam/JurassiCraft2#222]
I've found plants on top of wood, quartz slabs, and other non-dirt blocks

**Comment by Gamebrothers4** [comment]
Wich version?

**Comment by SanAndreasP** [comment]
Also screenshots would be really nice to see

**Comment by Cazsius** [comment]
Seeing as I cannot find this issue anywhere, and he has yet to reply with screenshots, closing issue.
