### ISSUE TITLE
Parasaurs Fight Back no Matter what

### ISSUE THREAD

**Issue by Anomalocaris101** [JurassiCraftTeam/JurassiCraft2#224]
Paralops fight back no matter what the attacker is while trikes run away, shouldnt it be the other way around?

**Comment by Anomalocaris101** [comment]
![2018-01-22_23 03 16](https://user-images.githubusercontent.com/35319486/35257686-c3e0a810-ffc8-11e7-8a58-3026f15a7d30.png)

**Comment by StevJubz** [comment]
Parasaurs

**Comment by StevJubz** [comment]
Not paralops dude

**Comment by Cazsius** [comment]
Old issue, not verified, waiting for someone to reopen.
