### ISSUE TITLE
Dinosaurs Don't eat

### ISSUE THREAD

**Issue by Flyerthe** [JurassiCraftTeam/JurassiCraft2#227]
Sometimes dinosaurs starve to death because they don't eat, even though they have lots of food.

**Comment by Gamebrothers4** [comment]
Is this in 2.3?

**Comment by Gamebrothers4** [comment]
2.1.3*

**Comment by Gamebrothers4** [comment]
Cannot reproduce

**Comment by SanAndreasP** [comment]
Can't reproduce it either
