### ISSUE TITLE
More Config Options

### ISSUE THREAD

**Issue by Ra-Zim** [JurassiCraftTeam/JurassiCraft2#229]
Hey, so I'm working on a modpack that's rather specific in its purpose, as in it's designed to limit resources that are just readily available. I want to include this mod, but the buildings that it generates are simply too overpowered.

So my suggestion is adding in more config options, ones to remove the building generation, or maybe give it a less... resourceful version. As well as one to disable vehicles at the least. I'll probably make do for now, but that's my suggestion.

**Comment by Cazsius** [comment]
Added in 1.12.2 + 1.11.2 latest release.
