### ISSUE TITLE
Won't Start Up

### ISSUE THREAD

**Issue by randomperson1210** [JurassiCraftTeam/JurassiCraft2#230]
I have tried a couple different versions of this mod with the corresponding forge installer on my mac. I get this screen for every one I have tried (blank minecraft screen with the dirt background and two blank grey buttons on the bottom). Other mods work, but not this one?
![screen shot 2018-01-28 at 4 03 30 pm](https://user-images.githubusercontent.com/35907023/35490676-7517c264-0445-11e8-8080-200b1e624393.png)

**Comment by gegy1000** [comment]
Can you send the `fml-client-latest.log` file after doing a launch where this happens? It is located in `<mc root>/logs`.

**Comment by SanAndreasP** [comment]
Do you still have issues?
If yes, please do as gegy1000 says and provide logs
If no (or you won't respond) I'm gonna close this issue and you'd have to open up a new issue if your problem isn't solved

**Comment by Cazsius** [comment]
Closed issue due to lack of response.
