### ISSUE TITLE
Big fat list of suggestions and bugs:

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#232]
Bugs:
- [x] Dinosaurs have trouble getting out of the water. Seems to happen mostly to species with leg articulation.
- [ ] Microraptor moves too slow and don't feed themselves all that correctly.
- [ ] Species like Gallimimus, Mussaurus, Velociraptor, Parasaurolophus and others tend to stick together a bit too much. Allow them to separate a bit. Seems to happen after they've flocked while in a confined space.
- [ ] Brachiosaurus, Gallimimus and Mussaurus all suffocate in blocks such as trees. I've seen this happen to Brachiosaurus with Araucaria; Gallimimus and Mussaurus suffocate with acacia trees.
- [ ] It feels like since 2.1.3 Gallimimus are moving a whole lot slower than in 2.1.2.

Suggestions:
- [ ] Gallimimus could leap over blocks if they're one block wide horizontally instead of jumping on top of it and then going back down.
More suggestions coming soon!

**Comment by Gamebrothers4** [comment]
1. They dont search for a shore so they stay in the water
2. This could happen because its so small
3. This depends on the herd ai probally
4. I will look after that one
5. I can check that for you

**Comment by Gamebrothers4** [comment]
1. Noted
