### ISSUE TITLE
Machine glitches

### ISSUE THREAD

**Issue by Gamebrothers4** [JurassiCraftTeam/JurassiCraft2#233]
- [ ] The gui of the bug farming crate is broken (it should put the crickets in the farming crate not drop it instantly it should drop it when its full

- [ ] Incubator doesnt show progress in the gui

- [ ] Cultivator doesnt show water progress and removes all items that go in it

- [ ] DNA extracter doesnt work at all

- [x] When you put a water bucket in the cleaning station and get it out again you crash = https://gyazo.com/7f10769868b5f282a72c2ed40ec68cb2

**Comment by SanAndreasP** [comment]
5. is fixed now
