### ISSUE TITLE
Gallimimus make for high ground

### ISSUE THREAD

**Issue by Flyerthe** [JurassiCraftTeam/JurassiCraft2#237]
Gallimimus seem to be attracted to mountains.
While flocked they make a beeline to the neerest high ground and it's really annoying to try to get them back.

**Comment by Gamebrothers4** [comment]
Is the "Enemie" comming from the mountain or the opposite side of the mountain?

**Comment by Codyrex78117** [comment]
Repeated issue

**Comment by Cazsius** [comment]
No one responded. Closing.
