### ISSUE TITLE
Suggested creatures #Feature request

### ISSUE THREAD

**Issue by EnderCorpsAlpha** [JurassiCraftTeam/JurassiCraft2#238]
Hi, Just here to say that I appreciate the quality of the mod - but it feels a little empty in terms of dinosaur species variety - So do you think there would be a possibility of there being dinosaurs added from the larger film universe? (So Like a Stegosaur, Spino, Anky Rugops, Mosasaur etc)

**Comment by Gamebrothers4** [comment]
JurassiCraft is working in different stages, We are working on adding more dinosaurs every stage :+1:. Like 2.1 Added Mussasaurus, Microraptor and Coelacanth.

**Comment by EnderCorpsAlpha** [comment]
So is there any place aside from here in which to keep up to date with the progress of the mod like a discord server or something?

**Comment by JCHyperion** [comment]
I highly suggest the Discord page, as we are almost constantly active there
https://discord.gg/2wDeMGR

**Comment by Cazsius** [comment]
No need to stay open, handled.
