### ISSUE TITLE
Minecraft wont start 1.10.2 with this mod

### ISSUE THREAD

**Issue by Zachasaur** [JurassiCraftTeam/JurassiCraft2#239]
when ever i try to start 1.10.2 with this mod on with llibrary and Jurassicraft 2.1 any version it always says this       : 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from mercurius_updater (mercurius_updater)      idk if its the mod but please help.

**Comment by SanAndreasP** [comment]
The error is not from our mod, but from Mercurius which ships with Forge.
In either case we'd need the latest.log file located in the logs folder.
