### ISSUE TITLE
Won't load for 1.7.10

### ISSUE THREAD

**Issue by ZombiChicken1703** [JurassiCraftTeam/JurassiCraft2#242]
So as I wanted to include more dinosaurs, I've downloaded the 1.7.10 (1.4.0 I think) version, which doesn't seem to load: when I start a new world in Minecraft, it says "Shutting Down Internal Server" before the end of the loading! Help

**Comment by gegy1000** [comment]
The 1.7.10 version is no longer supported, sorry.
