### ISSUE TITLE
Machines are not working - please fix

### ISSUE THREAD

**Issue by Codyrex78117** [JurassiCraftTeam/JurassiCraft2#244]

**Comment by SanAndreasP** [comment]
Fossil Grinder works now, Cleaning Station should already work

**Comment by Cazsius** [comment]
DNA Combinator, DNA Extractor, DNA Synthesizer, Embryonic Machine, Embryo Calcification Machine, Incubator all functional now.

All machines functional. Closing Issue

**Comment by SanAndreasP** [comment]
Please DO NOT use == ItemStack.EMPTY, use stack.isEmpty instead (it will also check if the stack has a size of 0 and/or the item is invalid)!

**Comment by 0SoggyMustache0** [comment]
Fixed issue, changed each instance of of the problem to the fixed version.
