### ISSUE TITLE
Set Feeder Default Slot to Top Left, not Top Right

### ISSUE THREAD

**Issue by Cazsius** [JurassiCraftTeam/JurassiCraft2#247]
Shift Click an item in, it seems more regular to go into the top right.

**Comment by 0SoggyMustache0** [comment]
Fixed in commit 4993cf3

**Comment by Wyn-Price** [comment]
The default slot is now bottom right

**Comment by Shrek5InTheatres2019** [comment]
fixed in @PT400C's pull request
