### ISSUE TITLE
Dinosaurs Excessively Spin

### ISSUE THREAD

**Issue by Cazsius** [JurassiCraftTeam/JurassiCraft2#253]
Upon Further investigation, it appears to be happening on or very close to slopes.

**Comment by Cazsius** [comment]
Also appears really badly when trying to escape water sometimes

**Comment by Gamebrothers4** [comment]
It could be fixed with the merge ill check it

**Comment by Wyn-Price** [comment]
Seems to be fixed. Can somone check again?

**Comment by Wyn-Price** [comment]
Can somone re-test this with the new code?

**Comment by Gamebrothers4** [comment]
I've retested it, It doesnt accure anymore ;)

**Comment by Gamebrothers4** [comment]
Wyn's code works, Doesnt accure anymore

**Comment by Wyn-Price** [comment]
Still in game
