### ISSUE TITLE
Carnivores aren't aggressive

### ISSUE THREAD

**Issue by JCHyperion** [JurassiCraftTeam/JurassiCraft2#255]
I have been in survival trying to get anything to attack me, but nothing does. No carnivores attack other animals nor other dinosaurs either.

**Comment by Cazsius** [comment]
I've had cases where carnivores kill animals... very sporadic, can't find reason, but sometimes they do kill.

**Comment by Wyn-Price** [comment]
Is that intended? or should they be attacking you always

**Comment by BrownBoiiWonder** [comment]
they should attack only when hungry or when attacked
