### ISSUE TITLE
Dinosaurs like water to much

### ISSUE THREAD

**Issue by Gamebrothers4** [JurassiCraftTeam/JurassiCraft2#260]
When dinos go into the water they just mostly don't want to get out unless there's like an prey on land

**Comment by Wyn-Price** [comment]
From testing things with the AI, the position is being set right, but it seems the dinos arnt able to get out the water as easily. it might be todo with the new water ai i wrote a few days ago.

**Comment by Wyn-Price** [comment]
Fixed in [45b761d](https://github.com/JurassiCraftTeam/JurassiCraft2/commit/45b761dbf3e35aac5944d3f5d3b92cbe8bfc3b79)
