### ISSUE TITLE
Improve this

### ISSUE THREAD

**Issue by Augustocroft** [JurassiCraftTeam/JurassiCraft2#261]
because you do not do version 2.1.3 for 1.7.10, I would really like it and I know that a lot of other people would also like it...

Thank you Croft

**Comment by BrownBoiiWonder** [comment]
We've repeated our stance on this.

The modding community is moving towards to 1.12.2 so we unfortunately cannot make a backport for a highly outdated MC version. Please refrain from asking us again and instead look out for the upcoming 1.12.2 port and next massive update ;) .
