### ISSUE TITLE
2.1.3 Bug Report and Suggestions

### ISSUE THREAD

**Issue by Frost214** [JurassiCraftTeam/JurassiCraft2#265]
This is just a post to increase awareness for issues with the mod that I have observed. For transparency, I have been playing on a world that was upgraded from v2.0.5 to v2.1.3.

[Breeding]
I have not been able to have creatures breed with one another. I have had a male and female velociraptor, for example, in the same enclosure ( fairly small ) for over 150 minecraft days. No where on the web have I seen anyone have their dinosaurs breed, and I have seen another post about this issue.

[Dinosaur Meat DNA Extraction]
Whenever trying to extract DNA from dinosaur meat onto a storage disc using a DNA extractor, each result comes out as velociraptor DNA, regardless of what dinosaur the meat belonged to.

[Cultivator Bug]
The cultivator is two blocks high. When breaking the cultivator from the top section, the cultivator drops as a texture-less box. When placing the cultivator in this state, it does not place on top of the surface you are looking at, rather, it replaces it, destroying whatever used to be there. This bug can be avoided by breaking the cultivator at the bottom section.

[Dinosaur Volume] - Suggestion
I am not sure if this is just something only I have an issue with, but I'd like to put this out there anyway. Dinosaurs are loud, extremely loud, at least for me. I can't lower my volume as I would cripple myself from practically muting other hostile mobs while just trying to normalize the volume of the screaming dinosaurs. Perhaps there can be a dinosaur volume in the config? This would be a great fix to those who also share this issue.

[Krill And Plankton]
When placing krill and plankton on the surface of the water, according to the wiki they should spread. I will continue writing with the assumption that they are meant to spread like grass does, but across the surface of the water. Krill and plankton do not spread in such a manner. Instead, any additional krill and plankton are just dropped as items and can be found either close by or far from the original source. For example, I have an underground aquarium where I placed krill and plankton on top of the water, and any new ones that multiply are found above ground as item drops.

[Coelacanth Feeding]
After placing krill and plankton on a fairly deep aquarium, all coelacanths eventually die from what I presume to be starvation as they never manage to reach the food source, staying only in the deep. As coelacanths are known for residing in deep waters, it would be unusual to demand that shallow tanks are constructed so they may find their food source. Perhaps they should venture to the surface whenever they are hungry? Or am I missing something else about keeping them fed?

[Breeding Suggestion]
This is a very minor suggestion, I would not care too much if it would never be implemented, but I'll just share it for good measure. When dinosaurs supposedly breed (according to the wiki; I've never seen any dinosaur breed in this version), they lay a clutch of eggs. Unless you pick up the eggs and replace them, the dinosaurs will hatch wild. So, if I have an enclosure of tamed velocirpators, for example, they would breed on their own and would hatch a few wild raptors without my interference? To prevent wild raptors from spawning in my tamed enclosures, I have to babysit them and make sure not to miss any eggs otherwise I'll have to murder a few unwanted dinos? I understand not making eggs automatically tamed, even with tamed parents, because it just naturally makes sense. However, I do not like the thought of having to constantly worry about dinosaurs breeding and producing wild family members. Perhaps there could be an option to toggle breeding on tamed dinosaurs?

[Electric Fence Suggestion]
With an unpowered fence, dinosaurs are able to climb over. With a powered fence, dinosaurs are repelled by a shock that damages. However, the shock eventually kills all the dinosaurs in the enclosure. Could there be a non-lethal setting that just disables a dinosaurs urge to escape or attack, or stuns them in a different way rather than damaging them to the point of death? The fences look amazing, but I and other players just fear using them as our dinosaurs might get themselves killed.

~[ ]~

These were just some things I had on my mind while playing the mod. I must say, after using this mod for so long, even before v2, the mod has never felt so amazing and well-polished. I liked the idea of the developers sticking to "quality over quantity" when making their creatures, and the mod is a shining example of what other minecraft mods should yearn to be. Thank you.

If anyone has any questions, comments or concerns, by all means post them. I'll reply whenever I can.

**Comment by Wyn-Price** [comment]
Breeding is planned on being redone. The current system is kinda funky and doesn't really work. Regarding the baby Dino's being tamed or not, they'll probably be tamed if the parents are. It makes the most sense i think, as in the real world (the very hypothetical real world), Dino's would copy what their parents do, and won't really be wild because they've never known what being wild is like. It also means you don't have to keep watch for baby Dino's, and means you can just let the dinos breed without requiring constant observation. 

Regarding the bugs, some of them may already be fixed, but I can check and fix all of them tommorow.

Also, thanks for this big issue/suggestion and going into detail about stuff. It really does help out.
