### ISSUE TITLE
Swimming isn't implemented/working

### ISSUE THREAD

**Issue by JCHyperion** [JurassiCraftTeam/JurassiCraft2#266]
As the title says, the swimming AI still seems to be missing. Creatures are floating, microraptors drown everywhere and go circles when they are, coelacanths are floating as well.

**Comment by Wyn-Price** [comment]
Microraptors are meant to drown. They can only swim if they're within 4 blocks from a non liquid block. They shouldn't be going in circles though

**Comment by guitarguy0124** [comment]
Mine are still constantly drowning.
