### ISSUE TITLE
No custom structures spawn

### ISSUE THREAD

**Issue by JCHyperion** [JurassiCraftTeam/JurassiCraft2#270]
There aren't any JC structures spawning, including the villager lab.

**Comment by Wyn-Price** [comment]
Structures arn't in the game anymore. This has already been decided

**Comment by gegy1000** [comment]
why?

**Comment by Wyn-Price** [comment]
No idea, wasn't my decision to make

**Comment by Wyn-Price** [comment]
Re-opening just to help track commits

**Comment by Wyn-Price** [comment]
Added for 1.12 in [00f4f29](https://github.com/JurassiCraftTeam/JurassiCraft2/commit/00f4f29553eb3eccdb29a15ba6709ea9b3b1b216), [d658e99](https://github.com/JurassiCraftTeam/JurassiCraft2/commit/d658e99614fcf9f235b7657521f3716b3be50ae3) and [567ce4e](https://github.com/JurassiCraftTeam/JurassiCraft2/commit/567ce4e4ea39eb39cd188ea0bbcf37bddcc957ae)
