### ISSUE TITLE
JC entities don’t play hit sounds

### ISSUE THREAD

**Issue by NeusFear** [JurassiCraftTeam/JurassiCraft2#273]
When damaging any JC entity the regular player-hit sound is played rather than the entities’ respective sound

**Comment by Cazsius** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/8u9O6QGx/1-test)

**Comment by Cazsius** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/8u9O6QGx/1-test)
