### ISSUE TITLE
Dinosaurs have an problem going up/down hills

### ISSUE THREAD

**Issue by Gamebrothers4** [JurassiCraftTeam/JurassiCraft2#274]
When they go up/down hills they just spasm out a bit it looks kindoff funky, They dont go up like their supposed to they go up in an kindoff angle and sometimes they just cant get up

**Comment by Gamebrothers4** [comment]
#194 Is like bassicly the same issue

**Comment by Wyn-Price** [comment]
Isn't #194 closed?

**Comment by Gamebrothers4** [comment]
Well it seems to accure again

**Comment by Wyn-Price** [comment]
So what is the issue? Can you record a video so it's easier for me to understand

**Comment by Gamebrothers4** [comment]
Ill try but im a bit sick
