### ISSUE TITLE
what to use to power incubators

### ISSUE THREAD

**Issue by ZombieHacker** [JurassiCraftTeam/JurassiCraft2#276]
when i go to incubate eggs i cant incubate then what mod do i use or is there a way to incubate them by its self?

**Comment by ZombieHacker** [comment]
1.10.2

**Comment by ZombieHacker** [comment]
2.1.3 fix

**Comment by ZombieHacker** [comment]
nvm i figured it out its peatmoss ok bye

**Comment by Gamebrothers4** [comment]
Check wiki next time
