### ISSUE TITLE
Another Random Crash

### ISSUE THREAD

**Issue by mxnmnm** [JurassiCraftTeam/JurassiCraft2#281]
MC- 1.12.2

Forge-1.12.2-14.23.4.2705

JurassiCraft-1.12.2-2.1.4 (v2)

Pastebin- https://pastebin.com/PMhNTib2

**Comment by Wyn-Price** [comment]
This seems to be an issue with forge/vanilla minecraft. I might just be tired so ill re-look into it

**Comment by Wyn-Price** [comment]
OK ive figured out whats wrong. Ill sort this out tommorow
