### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by starspunwolf** [JurassiCraftTeam/JurassiCraft2#285]
Server crash.

MC 1.12.2

forge-14.23.4.2705

Seems to be saying I need at least llibrary@[1.7.9,), but I'm using LLibrary 1.7.12

https://pastebin.com/G69V8azj

**Comment by NeusFear** [comment]
It’s currently required to be on 1.7.9 we will plan to update to the new version in a patch soon.

**Comment by Wyn-Price** [comment]
LLibary isnt being picked up by forge. Make sure its in the right folder.
