### ISSUE TITLE
Crash on Loading world

### ISSUE THREAD

**Issue by SyntaxError73** [JurassiCraftTeam/JurassiCraft2#288]
**Describe the bug**
It's a crash that happened when I upgraded Forge to 1.12.2-14.23.4.2707 after installing this mod. I have no idea if JC is the cause or not.

**To Reproduce**
Have all the mods I have and play on a new world...

**Crash Report or Logs**
https://pastebin.com/506bkCdf Crash
[latest.log](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2088284/latest.log)

**Additional context**
I play with over 140 mods, so any one of them could have broken the game.

**Comment by BrownBoiiWonder** [comment]
Did you install 2.1.4.1?

**Comment by SyntaxError73** [comment]
No i did not actually.. I had downloaded the version before the one you mentioned.. 
I'll try upgrading the mod and see what happens.

**Comment by BrownBoiiWonder** [comment]
Yeah it has fixes that might help

**Comment by Wyn-Price** [comment]
That won't help. What it looks like is another mods ASM isn't working with this version of forge. Try figuring out which one then reporting it to them

**Comment by Wyn-Price** [comment]
It's any mod that changes World#getRawLight

**Comment by SyntaxError73** [comment]
Prolly Dynamic lights then....

I'll remove that and see if it works

**Comment by Wyn-Price** [comment]
If it is, you'll need to wait for them to update to the latest forge version

**Comment by SyntaxError73** [comment]
they are already on 1.12.2... so i am going to try without Dynamic lights, and if it works, upgrade that mod and see if it still works
