### ISSUE TITLE
Fish again.

### ISSUE THREAD

**Issue by StarWarsDinosaur** [JurassiCraftTeam/JurassiCraft2#290]
impossible to make coelacanth.

**Comment by Wyn-Price** [comment]
What do you mean. Coelacanths, last time I checked, are made with the cultivate machine? (Unlike other dinos)

**Comment by StarWarsDinosaur** [comment]
Doesn’t work

**Comment by Wyn-Price** [comment]
Ill make a JEI plugin for this. It might be in a later update
