### ISSUE TITLE
Unable to tell dinosaurs to sit, crash when Dinosaurs are sneak right clicked (may be conflicting with other mods)

### ISSUE THREAD

**Issue by mcnetherbeast** [JurassiCraftTeam/JurassiCraft2#295]
Hello, I am experiencing a problem with sneak right clicking dinosaurs which results in a crash. Also dinosaurs cannot be told to sit or run. There may be mods conflicting with this
[crash-2018-06-12_17.26.51-server.txt](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2096226/crash-2018-06-12_17.26.51-server.txt)

**Comment by Wyn-Price** [comment]
Update to the latest version. It should fix these issues

**Comment by mcnetherbeast** [comment]
I don't know about that, I switched to the first 1.12.2 port from the newest release because of the crashes and issues

**Comment by Wyn-Price** [comment]
Are you sure the crash report is the same from the latest version

**Comment by mcnetherbeast** [comment]
It is not from the latest version, this is from 2.1.4, but I wasn't playing on 2.1.6 and had the same issues.

**Comment by Wyn-Price** [comment]
Can you send the crash report from when you're playing on the latest version?

**Comment by mcnetherbeast** [comment]
I am no longer experiencing crashes when shift right clicking dinosaurs, however, I still am not able tell dinosaurs to follow or stay, when a right click them nothing happens

**Comment by Wyn-Price** [comment]
@mcnetherbeast are you sure you own the dinosaur. It should say stuff in chat if you dont

**Comment by Wyn-Price** [comment]
are you right clicking with an empty hand?

**Comment by mcnetherbeast** [comment]
do I have too?

**Comment by Wyn-Price** [comment]
Right clicking with an empty hand brings up the command GUI. If you right click with an item, it'll try to process that item instead

**Comment by mcnetherbeast** [comment]
Understood, I was confused about the hand, and it appears as if the crash does not happen anymore when I shift right click for some mysterious reason. Thank you.

**Comment by mcnetherbeast** [comment]
I will now close this issue
