### ISSUE TITLE
Ford Explorer Won’t Go Up or Down Hills

### ISSUE THREAD

**Issue by Bradley19964** [JurassiCraftTeam/JurassiCraft2#296]
The Ford Explorer jumps off the track anytime it goes uphill or downhill. Does fine on flat land. Using 1.12.2 client

**Comment by Wyn-Price** [comment]
Could you describe in more detail first? Maybe send a photo of the rails?

**Comment by Bradley19964** [comment]
When the explorer is riding on the rails on flat land it does great but when it gets to a hill and starts to go up it will stop, jump off track, and spin around and just sit there. Whenever it goes downhill it will just stop and won't move. Sometimes it will jump off of the track but mainly just stops. Heres a couple GIF's showing what it does. Thank you!


![going downhill](https://user-images.githubusercontent.com/39752926/41427903-068151cc-6fce-11e8-907a-7428cdc2be0d.gif)
![going uphill](https://user-images.githubusercontent.com/39752926/41427904-06a1f9fe-6fce-11e8-81f7-ee6f3ea33a6d.gif)
