### ISSUE TITLE
Fossils  Don't Drop anything

### ISSUE THREAD

**Issue by FlashOni** [JurassiCraftTeam/JurassiCraft2#297]
I went into a game with a few other mods i can give the mod list if you need it but i was on the newest version (JurassiCraft-1.12.2-2.1.6.jar) And i broke some fossils first with a iron pickaxe then with a diamond pickaxe and 16 fossils with the diamond and 13 with the iron pick and no fossils dropped (You need the bones to get dna i think) And i don't wanna cheat them cuz that isn't really fun.

**Comment by Wyn-Price** [comment]
The regular fossils dont drop anything. You have to use a `plaster and bandage` item in order to turn it into an encased fossil, which you then use to make the bones and so on. Im going to make a tutorial now on how to get dinosaurs.

**Comment by Wyn-Price** [comment]
@FlashOni https://github.com/JurassiCraftTeam/JurassiCraft2/blob/master-1.12.2/tutorials/How%20To%20Make%20Dinosaurs.md
