### ISSUE TITLE
(Suggestion) Option to Not Leave Corpses

### ISSUE THREAD

**Issue by Boolyman** [JurassiCraftTeam/JurassiCraft2#300]
The number of dead dinosaur corpses is tremendous, especially for things like mob farms, or packs where mobs fight each other.  Can you please include an option to despawn the corpses after a much shorter period of time, or not have them turn into corpses at all?  I know they are a source for the bones, but we as pack makers can find a way around that.  We can not find a way around the TPS issues caused by so many item entities laying around.

**Comment by Cazsius** [comment]
This has been added, will be released soon.
