### ISSUE TITLE
Crash on SP world creation

### ISSUE THREAD

**Issue by Beanius** [JurassiCraftTeam/JurassiCraft2#302]
https://paste.dimdev.org/mazuwivaqa.mccrash

**Comment by Wyn-Price** [comment]
This happens when another mod locks the loot table by replacing it. This isn't technically our fault but I can push a fix for it

**Comment by Beanius** [comment]
That would be amazing!! :D Been anticipated for a 1.12 vers, so would appreciate it a lot if you would go through the length of fixing the loot table issue yah B)

**Comment by Wyn-Price** [comment]
fixing it now. will release a new version today

**Comment by Beanius** [comment]
Superb!

**Comment by Beanius** [comment]
When will it be uploaded?

**Comment by Wyn-Price** [comment]
Ill try and push a build tonight, seeing as little to no bugs have been reported

**Comment by Beanius** [comment]
super!
