### ISSUE TITLE
Jurassic craft fallen kingdom

### ISSUE THREAD

**Issue by Augustocroft** [JurassiCraftTeam/JurassiCraft2#303]
when the version in which we will have the dinosaurs of the fallen kingdom will come out?Do you have any predictions?

**Comment by Wyn-Price** [comment]
there isnt / cant be a predicted time. Making a dinosaur takes a ton of effort, to animate, texture, model and code in its behaviours. The process of making a dinosaur is becoming shorter, but noone can say for certian when everything is done to a standard where we are happy to release it. If I had to guess, Id give it a couple of months, maybe more maybe less

**Comment by BrownBoiiWonder** [comment]
This is a bug/crash report tracker not a place to pester devs when they'll release updates. I'd suggest you post any bugs next time you stumble upon while playing with the mod.
