### ISSUE TITLE
infant dinosaurs lay eggs

### ISSUE THREAD

**Issue by EnderiumSmith** [JurassiCraftTeam/JurassiCraft2#304]
So i made a pair of triceratops and brachiosaurs. when i went to check on them later it appeared that the triceratops have duplicated and later i came to find 5 brachiosaurs of one gender. later i found a nest of brachiosaur eggs and i saw one lay more eggs. they are 3 days old max. weird thing is they appear to have an equal number of males and famales.

**Comment by DoveGirl777** [comment]
i have this problem too
