### ISSUE TITLE
tamed dinos

### ISSUE THREAD

**Issue by DoveGirl777** [JurassiCraftTeam/JurassiCraft2#305]
whenever I right click a tamed dino, i can't edit it so the tamed dinos can follow, stay, or free roam whenever I walk.  I keep right clicking it but nothing happens.

**Comment by Wyn-Price** [comment]
Can you send the logs? it should be under `.minecraft/logs/fml-latest-client.log`

**Comment by Wyn-Price** [comment]
Can you load a world, right click a dinosaur then send the log. Also, can you send it via pastebin.com or gist.github.com

**Comment by DoveGirl777** [comment]
ok

**Comment by DoveGirl777** [comment]
i think i know what happened.... i had an old version of jurassicraft

**Comment by DoveGirl777** [comment]
thats why it didn't work

**Comment by DoveGirl777** [comment]
sorry to bother you

**Comment by Wyn-Price** [comment]
heh its fine
