### ISSUE TITLE
Encased Coelacanth Fossil 

### ISSUE THREAD

**Issue by Conquerorelmas** [JurassiCraftTeam/JurassiCraft2#309]
Salut ! Je viens reporter quelques bugs de JurassiCraft dernière version en 1.12.2
Deux bugs notamment, et une question.
Premier bug : Lorsqu'on met du papier sur le fossile et qu'on le ramasse, c'est presque toujours du Fossile de Cœlacanthe (à 90%), ou alors un bloc fossile qu'on a déjà en main (8%) et une fois, j'ai eu plein de fossiles différents (2% du temps).
Deuxième bug : Lorsqu'on veut transformer les blocs fossiles en morceau de fossiles dans la machine, on peut usebug :
Il suffit de placer un bloc du dinosaure souhaité en premier lieu, mettre en route la machine, puis, en cours de route, remplacer le bloc de dinosaure souhaité (en général rare) par d'autres blocs de dinosaures.
Ceux-ci donnerait des fragments du dinosaure souhaité.
Donc avec un bloc de Massu et 32 Coelacanthe, on peut conserver son bloc Massu mais s'en servir pour transformer les blocs Coelacanthe en faisant en sorte qu'ils donnent des fragments Massu. Tu as réussi à comprendre x) ?
Et ma question : A quoi servent les trois types d'insectes, vu qu'on ne peut pas nourrir les dinos ou les mettre dans la machine à nourrir ?
De plus, la machine de culture d'insectes n'est pas craftable pour moi.

Hello ! I just post a few bugs of JurassiCraft latest version in 1.12.2
Two particular bugs, and a question.
First bug: When you put paper on the fossil and collect it, it's almost always Coelacanth Fossil (90%), or a fossil block that we already have in hand (8%) and once, I had lots of different fossils (2% of the time).
Second bug: When we want to turn the fossil blocks into a piece of fossil in the machine, we can usebug:
Simply place a desired dinosaur block in the first place, start the machine, then, along the way, replace the desired dinosaur block (usually rare) with other dinosaur blocks.
These would give fragments of the desired dinosaur.
So with a block of Massu and Coelacanthe, we can keep its Massu block but use it to transform the Coelacanth blocks by making sure that they give Massu fragments. Did you manage to understand x)?
And my question: What are the three types of insects used for, since we can not feed the dinos or put them in the machine to feed?
Plus, the insect growing machine is not craftable for me.

**Comment by Wyn-Price** [comment]
Im confused at what you mean. Maybe make a video showing what goes wrong?

**Comment by Wyn-Price** [comment]
Regarding the `insect growing machine`, i assume you mean the bug create. The recipe for that is: 
![image](https://user-images.githubusercontent.com/15876682/41820360-a57bde6c-77c8-11e8-8ddd-b7b3eeee677b.png)

**Comment by Cazsius** [comment]
The Fossils spawns are based off of the time period they lived, and Y level. It is not based off when you mine the fossil. This is not a bug, Coelacanth fossils are just fairly common.
