### ISSUE TITLE
Crashed again

### ISSUE THREAD

**Issue by DoveGirl777** [JurassiCraftTeam/JurassiCraft2#312]
My game crashed again......please tell me what to do in order to fix this problem

**Comment by DoveGirl777** [comment]
should I delete this world?

**Comment by Wyn-Price** [comment]
Hey the latest version

**Comment by DoveGirl777** [comment]
this only happens with this world.
Seed: -1789556842

**Comment by DoveGirl777** [comment]
yea this is the latest version

**Comment by Wyn-Price** [comment]
It's notm. You have 2.1.7, the latest is 2.1.8
