### ISSUE TITLE
kicked from server placing a hatched Tyrannosaurus egg

### ISSUE THREAD

**Issue by Ironic8b498** [JurassiCraftTeam/JurassiCraft2#317]
I was kicked from server placing a hatched Tyrannosaurus egg, and I can't log in, other players can log into          the server and play. The server is still being developed for public use. Was hoping to let players on soon

https://paste.extendedclip.com/izuqoyejay.md

**Comment by Wyn-Price** [comment]
In the log you sent, there was no crash. Are you sure that's the right log?

**Comment by Ironic8b498** [comment]
never said crash. I keep getting kicked can't join the server
if delete my player data I will log in at spawn but when I warp to where I placed the egg I get kicked, or if any player enters that area

**Comment by Wyn-Price** [comment]
Can you send the client and server log. In the log you sent, there wasn't any issues

**Comment by Ironic8b498** [comment]
client log?

**Comment by Ironic8b498** [comment]
the server logs are no different from what I sent you
I just can't join server at my base

**Comment by Wyn-Price** [comment]
Yeh. Should be located in `.minecraft/logs/fml-client-latest.log`. I might have spelt the file name wrong

**Comment by Ironic8b498** [comment]
I was on my lobby server and tried to change to the forge server at [13:12:59] got tons of stuff, some things were from a mod I removed last month.
https://paste.extendedclip.com/kalijirefi.md

**Comment by Wyn-Price** [comment]
In that log you weren't kicked

**Comment by Ironic8b498** [comment]
bungeecord has this for a reason
![untitled](https://user-images.githubusercontent.com/6716130/41990927-d3565bf0-7a11-11e8-8e3d-102dc09710b0.png)

**Comment by Wyn-Price** [comment]
Theres nothing in the logs that you sent me that can help me at all. Ill look into it but without proper logs it could be difficult

**Comment by Ironic8b498** [comment]
If I delete my data file, I can play fine on the server just can't go to my base.

**Comment by Wyn-Price** [comment]
Delete your data file, go to the your base, then once kicked send me the client log

**Comment by Ironic8b498** [comment]
home took me to my old base, warp lab is new base where I have the dinosaur pens.
https://paste.extendedclip.com/fuxazogono.md

this is when I placed a second dinosaur egg and got kicked, I shut down server and deleted player data and log back in
https://paste.extendedclip.com/axoriburet.md

**Comment by Wyn-Price** [comment]
I cant help you. None of the logs show any sign of there being an issue. Can you try without bungeecord, on a seperate server?

**Comment by Ironic8b498** [comment]
I have it making backups every 4 hours, guess I will have to roll back, thanks for helping

**Comment by Cazsius** [comment]
SpigotMC/BungeeCord has said this is on our end, we will need to investigate.
