### ISSUE TITLE
Coelacanth eggs can be made in the embronic calcification machine 1.12.2 jurassicraft 2.1.8

### ISSUE THREAD

**Issue by F34RxPredator** [JurassiCraftTeam/JurassiCraft2#319]
I seem to be getting the Coelacanth eggs using the embronic calcification machine
![2018-06-27_22 49 24](https://user-images.githubusercontent.com/39810191/42012259-28c8d644-7a8f-11e8-83e4-946fc163f400.png)

**Comment by Cazsius** [comment]
This is only a visual issue, and not actually possible to do. This is fixed in the latest dev build.
