### ISSUE TITLE
No 1.10.2 options

### ISSUE THREAD

**Issue by JHKDinos** [JurassiCraftTeam/JurassiCraft2#320]
I love this mod and i love a lot of the designs and details you put in, i recently opened a server and need 1.10.2 mods i will support your changes if you go into 1.11 and 1.12 permanently but i think some other people would agree with having more 1.10.2!

**Comment by Wyn-Price** [comment]
I'm sorry but no. Having to backport features between 1.12 and 1.11 as it is is difficult and can end up taking way too much time. If I add 1.10 in the mix, then due to 1.10 being very internally different to 1.11 & 1.12, then I'd have to rewrite every feature just for a niche audience.
