### ISSUE TITLE
Ticking entity crash regarding herds

### ISSUE THREAD

**Issue by darthvader45** [JurassiCraftTeam/JurassiCraft2#322]
Apparently tried to spawn T.Rex with spawn egg, and something in the herd code caused a crash.

https://pastebin.com/3u2U3Wsq

**Comment by Gamebrothers4** [comment]
Version?

**Comment by darthvader45** [comment]
2.1.8, and client.

**Comment by Gamebrothers4** [comment]
1.12.2 or 1.11.2?

**Comment by darthvader45** [comment]
1.12.2

**Comment by Gamebrothers4** [comment]
Do you have discord, so we can talk further from their how the issue accured exetra

**Comment by darthvader45** [comment]
Yeah, I have it set to start in the background on boot as well.

**Comment by Gamebrothers4** [comment]
Could you send your DiscordName#thingy?

**Comment by darthvader45** [comment]
Last_Dovahkiin#5062

**Comment by PT400C** [comment]
Same issue for me, but without T-Rexes. The game just crashes when getting in the area around a chunk with dinosaurs. Apparently for me it's the Brachiosaurus. My discord identifiers are: PT400C#8363

**Comment by darthvader45** [comment]
I was playing around with a few naturally hatched t.rexes, and then tried spawning one more in via spawn egg, and the game crashed.

**Comment by Shrek5InTheatres2019** [comment]
this will be fixed in the next build i believe, judging from @PT400C's pull request. You can be looking out for that soon
