### ISSUE TITLE
Velociraptors dying from unknown reasons

### ISSUE THREAD

**Issue by TheInsaneGamer** [JurassiCraftTeam/JurassiCraft2#323]
Whether it is spawned in or hatched from incubators, they all end up getting hurt and then eventually **die off.** I've made sure there were no poisonous plants in the paddock and nothing else they could die from 
but they still manage to die off -_- The other dinosaurs seem to do fine though.
Also, they do not just get hurt and die. They get hurt, regen, hurt, regen and repeat and it takes forever for them to actually die, but there is nothing to both hurt and regen their hearts... Is this a bug i can fix?
I also use the 1.8.9 prelease 5 and 0.8.0 Llibrary

**Comment by Gamebrothers4** [comment]
We do not support the prereleases
