### ISSUE TITLE
Freeze with dinosaur death

### ISSUE THREAD

**Issue by Flemmli97** [JurassiCraftTeam/JurassiCraft2#324]
Minecraft: 1.12
Forge: 1.12.2-forge1.12.2-14.23.4.2705
Jurassicraft: JurassiCraft-1.12.2-2.1.8

I noticed what when a dinosaur dies it can freeze my game. I don't know the exact circumstances that causes this since in a test world dead dinos did't caused it. There is neither any trace in the log nor a crash log since the game simply does not respond and i have to quit it using the task manager. 

The mod was played in a private modpack and i figured it was jurassicraft cause 1.  right after a velociraptor of mine died it froze and 2. everything worked fine after removing jurassicraft. 

The issue might be related to #314

**Comment by Wyn-Price** [comment]
Does it ever unfreeze? How much ram/memory have you allocated to the game

**Comment by Flemmli97** [comment]
no, i have 3g allocated, it usually is around 1.5g

**Comment by Gamebrothers4** [comment]
Is this server sided?

**Comment by Wyn-Price** [comment]
It can't be server sided

**Comment by Wyn-Price** [comment]
@Flemmli97 can you open up f3 screen, then kill a dinosaur and see what the mem usage goes to

**Comment by Flemmli97** [comment]
no, nothing regarding the memory changed. can dinos starve to death? this is probably that kind of bug that happens in a 1 out of 1000 cases...

**Comment by Wyn-Price** [comment]
Yeh I think they can starve. But that shouldn't effect freezing or anything

**Comment by Cazsius** [comment]
No response.
