### ISSUE TITLE
extreme lag

### ISSUE THREAD

**Issue by max04max** [JurassiCraftTeam/JurassiCraft2#325]
I am trying to run this mod pack but am having a lot of lag. I can run other much more intensive mod pack with a steady 60 fps and have 5gb of ram allocated. I'm not sure what to do, please help.

**Comment by Wyn-Price** [comment]
When you remove all other mods, is there still an issue

**Comment by max04max** [comment]
I am not sure but I am on you official mod pack that I have launched from
the twitch launcher.

**Comment by max04max** [comment]
I ran a new client with just JurassiCraft and had a steady 80-100 fps

**Comment by Wyn-Price** [comment]
If you can figure out what other mods are causing the lag, then see if having jurassicraft makes anything worse

**Comment by max04max** [comment]
I may have figured it out. By removing pams harvest craft I have somewhere
between 100-300 fps. I’m getting huge lag spikes when loading in new chunks
and journey maps shows a bunch of seemingly random loaded chunks. Very
strange but currently playable.

**Comment by Wyn-Price** [comment]
Press f3 and look at the memory usage. It might be hitting 100%, which will cause it to freeze

**Comment by max04max** [comment]
Nope this was not the problem I never reached anywhere near 100% and I had 6gb of ram allocated. Not sure but I tweaked some settings and now have about 150fps. Very odd butt thanks for the help and fast replies.

**Comment by Gamebrothers4** [comment]
Is this fixed now?
