### ISSUE TITLE
Female raptors not spawning

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1** [JurassiCraftTeam/JurassiCraft2#328]
i leave it with 64 moss in the incubator and put it on the highest percent and it still gave me a male
even 3 didnt work,along with me trying to tame a wild one,but to no avail
whats happening?

**Comment by JCHyperion** [comment]
It's not possible to tame wild dinosaurs. Also, you need Peat moss for the incubator, not regular moss. Peat moss is made using peat and surrounding it with moss in a crafting table.
I hope you're informed with this.
