### ISSUE TITLE
when i bredd goats s bsby doesnt come out

### ISSUE THREAD

**Issue by Slipperydane** [JurassiCraftTeam/JurassiCraft2#331]
ok so when I get my wheat and breed my goats no baby comes out can you pls fix that. edit: 1.12.2 1.9

**Comment by Shrek5InTheatres2019** [comment]
I tested this, and i cannot recreate the bug, can you maybe expand on this a little bit? you use wheat, right? and you give it to _both_ goats?

**Comment by Slipperydane** [comment]
yes i give my 2 goats 1 wheat each than i think there going to make a baby but nothing happens

**Comment by Shrek5InTheatres2019** [comment]
Are you able to supply a video of this happening? maybe a log?

**Comment by Cazsius** [comment]
If you need further support, please join our discord. https://discord.gg/RBR6XZj
This has been tested to be working fine.
