### ISSUE TITLE
Velociraptor Packs

### ISSUE THREAD

**Issue by DeinoRaptor** [JurassiCraftTeam/JurassiCraft2#332]
Dinosaurs seem to not move in certain spots and in water. They seem to get stuck.
Same for being in pits.

Also, sometimes Velociraptors dont hunt in packs. Maybe its just me... but sometimes

**Comment by Cazsius** [comment]
Dinosaurs stuck in water has been fixed.

Velociraptors will attack the same target if they are within range.
