### ISSUE TITLE
Triceratops sometimes randomly shaking heads

### ISSUE THREAD

**Issue by PT400C** [JurassiCraftTeam/JurassiCraft2#333]
- I'm using the latest 1.12.2 version of the mod

Sometimes, adolescent Triceratops randomly shake their heads. I wasn't able to find out why they do it, but it might by due to the surrounding terrain.

Here are some pictures:
[First](https://image.ibb.co/deSaZJ/2018_07_20_07_58_07.png)
[Second](https://image.ibb.co/ecPuTd/2018_07_20_07_57_48.png)

I hope this helps you guys ;)

**Comment by Cazsius** [comment]
This should be fixed in the latest dev build.
