### ISSUE TITLE
Sea Lampreys can't give DNA

### ISSUE THREAD

**Issue by darthvader45** [JurassiCraftTeam/JurassiCraft2#337]
Tried putting a Sea Lamprey in the DNA Extractor, nothing happened.

What should ideally happen:

Progress bar fills, and chance of coelacanth DNA, fish, ice, etc.

**Comment by Shrek5InTheatres2019** [comment]
Can you supply more information? I'm unable to reproduce the bug. Maybe a screen recording or a log?

**Comment by darthvader45** [comment]
Try putting a sea lamprey into a DNA extractor, and you'll see.

JC version 2.1.9

**Comment by Shrek5InTheatres2019** [comment]
I'm on the development version. Have you put an empty disk into the DNA extractor as well?

**Comment by darthvader45** [comment]
Oh, maybe that's why.  Damn, never thought of that.  Thanks.

Golden rule in Minecraft: Never dig straight down.

**Comment by darthvader45** [comment]
Done, you're right.  Shouldn't have been so stupid.

Golden rule in Minecraft: Never dig straight down.

**Comment by Shrek5InTheatres2019** [comment]
It's fine, just remember to check the wiki page(or JEI/NEI page) on a block before posting an issue about it, to make sure you're using the block correctly
