### ISSUE TITLE
List of problems (Stuck, incorrect AI)

### ISSUE THREAD

**Issue by DeinoRaptor** [JurassiCraftTeam/JurassiCraft2#341]
I have a various list of problems of JC. I am not sure of the cause, but I think some are having the same problem

1. Dinosaurs stuck in water. This one is for lots of people, but sometimes dinosaurs can be stuck in water and die, and sometimes some dinosaurs just randomly get stuck and dont move, like they should be sitting but they aren't

2. Some carnivorous dinosaurs aren't attacking players when provoked. Sometimes this problem occurs for small groups or individual dinosaurs. I attack a rex and like a normal pig, it runs in circles. Not just that but other dinosaurs (all carnivores). The only time they attack is when they are in big packs.

3. Car Rail is glitchy. It cant go upwards, or turn bare turns. It generally is a little weird.

4. Dinosaur aging slowed? Is it me or dinosaur aging is extremely slow. Unless that is purposely. This might just be a feature.

5. Some dinosaurs just simply breed and that's it. They don't breed anymore. Unless they can't lay eggs if they still have babies/juveniles.

**Comment by reuxertz** [comment]
This issue was broken up into multiple.
