### ISSUE TITLE
Car Rail is glitchy

### ISSUE THREAD

**Issue by reuxertz** [JurassiCraftTeam/JurassiCraft2#344]
Car Rail is glitchy. It cant go upwards, or turn bare turns. It generally is a little weird.

**Comment by TheMysteriousGray** [comment]
I've had this too. It's a crapshoot whether the tour rail will climb hills or not, and oftentimes it will climb a hill perfectly and then fail to do so an hour later, with absolutely nothing changing

**Comment by dadinosaur** [comment]
I have the same problem except it cant make right turns so I cant make the car go on the track unless the track was all left turns

**Comment by Cazsius** [comment]
This is very similar to #335 I am going to close this, and move info there.
