### ISSUE TITLE
Disable Tour Rails Config option not working on Singleplayer

### ISSUE THREAD

**Issue by TheMysteriousGray** [JurassiCraftTeam/JurassiCraft2#354]
I downloaded 2.1.12 to test out the new bugfixes. Worked fine the first two times I laucnhed the game, but now it always crashes upon launching my MC profile. Here's the crash report:

[crash-2018-07-26_18.51.06-client.txt](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2233933/crash-2018-07-26_18.51.06-client.txt)

**Comment by Shrek5InTheatres2019** [comment]
Can you find and show your jurassicraft.cfg? it should be in the config folder in the minecraft folder

**Comment by Shrek5InTheatres2019** [comment]
# Please?

**Comment by TheMysteriousGray** [comment]
sorry, was off doing... _things._


[jurassicraft.txt](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2238328/jurassicraft.txt)

**Comment by Shrek5InTheatres2019** [comment]
In the file in your minecraft directory, please change the line
`B:"Enable Tour Rail Blocks"=false` to `B:"Enable Tour Rail Blocks"=true` and see if that helps

**Comment by jaz000** [comment]
I had exactly this problem and that config fix fixed the problem for me.

Background - I am removing vehicles because I am using vehicles from car mod powered by fuels from immersive engineering, so thought I might want to turn that feature off ...

**Comment by Shrek5InTheatres2019** [comment]
That config value works the way it's supposed to exclusively on servers it seems
