### ISSUE TITLE
Dinosaur Orders frozen

### ISSUE THREAD

**Issue by GalazyBoiii** [JurassiCraftTeam/JurassiCraft2#359]
Hello, I play on the official JC server. On the server, my Triceratops and Mussaurus' orders are being weird.    (The Triceratops is a 3-4 day old female, and the Mussa is a 1-2 day old male). When I order the Trike to sit, it does, but when I go into the order list again, it still has "Wander" selected. The same goes with my Mussa. I don't know why this is happening, and I've tried relogging to fix it, and it doesn't work. I've heard other players are having this as well, but I don't know dino specifics for them. If you could try and get this fixed, it'd be really appreciated! Thanks!

**Comment by PT400C** [comment]
This is actually a known bug. If I've got some time, I'll review that one.

**Comment by PT400C** [comment]
I'm in charge of that issue and will publish a PR soon.
