### ISSUE TITLE
Issues and improvements for dinosaur to dinosaur interactions and hunting

### ISSUE THREAD

**Issue by EmperorPlebpatine** [JurassiCraftTeam/JurassiCraft2#368]
We can't always keep the species that fight separated all the time. I've observed carefully on the predator - prey interactions in-game. My version of JurassiCraft is 2.1.12.

Brachiosaurus:
- Velociraptor doesn't attack it, regardless of gender of either dinosaur.
- Dilophosaurus doesn't attack it, regardless of gender of either dinosaur.
- Tyrannosaurus doesn't attack it, regardless of gender of either dinosaur.
- Microraptor doesn't attack it, regardless of gender of either dinosaur.
Brachiosaurus is not attacked by any carnivore under any circumstances; this is perfect, as it would be too big to realistically hunt.

Parasaurolophus:
- Velociraptor attacks it, regardless of gender of either dinosaur.
- Dilophosaurus attacks it, regardless of gender of either dinosaur.
- Tyrannosaurus attacks it, regardless of gender of either dinosaur.
- Microraptor doesn't attack it, regardless of gender of either dinosaur.
Parasaurolophus has only shown a reaction to getting attacked by dilophosaurus, counter attacking it almost instantly. However, otherwise, it stays complete still, allowing tyrannosaurus and velociraptor to kill it. Parasaurolophus should run away when attacked by tyrannosaurus and velociraptor.

Gallimimus:
- Velociraptor attacks it, regardless of gender of either dinosaur.
- Dilophosaurus attacks it, regardless of gender of either dinosaur.
- Tyrannosaurus attacks it, regardless of gender of either dinosaur.
- Microraptor doesn't attack it, regardless of gender of either dinosaur.
Gallimimus is one of the few herbivorous dinosaurs in the mod who currently has a chance to survive a predator attack. They automatically flee from any carnivores, but only when the carnivores seemingly target them. Gallimimus have a better chance of escape if they're in a large flock. A pair of them ran in circles when attacked by a pair of velociraptor.

Mussaurus:
- Velociraptor attacks it, regardless of gender of either dinosaur.
- Dilophosaurus attacks it, regardless of gender of either dinosaur.
- Tyrannosaurus attacks it, regardless of gender of either dinosaur.
- Microraptor doesn't attack it, regardless of gender of either dinosaur.
Like gallimimus, mussaurus seems to run in the same scenarios as gallimimus. Mussaurus don't seem to have the same issue where if there's more than one but not too many they'll essentially run in circles. Mussaurus' interactions of predator and prey, like brachiosaurus, require no changes.

Triceratops:
- Velociraptor attacks it, regardless of gender of either dinosaur.
- Dilophosaurus attacks it, regardless of gender of either dinosaur.
- Tyrannosaurus attacks it, regardless of gender of either dinosaur.
- Microraptor doesn't attack it, regardless of gender of either dinosaur.
Triceratops can only defend itself when in a herd. If alone, a triceratops will have some form of "cool down" after being punched where it won't do anything, but then proceed to attack the creature that attacked it. Problem is, the cool down lasts too long and the carnivore lands a hit again, resulting in a lone triceratops dying every time to a carnivore if done right. Furthermore, the herd of triceratops defended the one in pain, but after started flocking and proceeded to ignore getting attacked again. Testing with a lone triceratops and tyrannosaurus, the triceratops shows little to no signs of even minding getting attacked.

None of the results here seem to be affected by the world's difficulty.

**Comment by Cazsius** [comment]
This is old, would need to be retested, closing until then.
