### ISSUE TITLE
Glitched cultivator

### ISSUE THREAD

**Issue by AJPhoenix07** [JurassiCraftTeam/JurassiCraft2#370]
If you break the top part of a cultivator you get a glitched block and if you place it down it breaks the block under it

**Comment by PT400C** [comment]
Which version does this refer to? 1.11.2 or 1.12.2?

**Comment by PT400C** [comment]
Okay. For the 1.12.2 version, I fixed this issue right now 👍 

Thank you VERY much for that report! :)

**Comment by AJPhoenix07** [comment]
1.12.2

**Comment by AJPhoenix07** [comment]
o
