### ISSUE TITLE
Suggestions for dinosaur transport

### ISSUE THREAD

**Issue by EmperorPlebpatine** [JurassiCraftTeam/JurassiCraft2#375]
I've realized that JurassiCraft (almost) has it all. Feeders, electric fences, paddock signs, jeep wranglers, ford explorers and their tour tracks, etc., but there's always one thing that can sometimes come off as a problem; moving dinosaurs from places to places quickly and safely. Here are some suggestions for how we can transport dinosaurs.

On-land transport:
This would require the player to obtain an item that could be preferably named the dinosaur transport truck. When a dinosaur is tranquilized and it falls into a sleeping position, the player can right click it with either a small cage, medium cage, or large cage to transport the dinosaur in. This'll put the cage around the dinosaur. You can then drive the dinosaur transport truck into the cage so it mounts the truck like a mob mounts a minecart. You could be able to press a specific button to "dismount" the dinosaur cage in the paddock that you want it in.

Air born transport:
This would be similar to Jurassic World: Evolution's transport method. You tranquilize a dinosaur, and then you right click it with a small, medium, or large cage. You can then attach it to the helicopter through a lead and carry the dinosaur through the sky. You can then click a specific button to de-attach the cage and drop it in the paddock you want. This should make the dinosaur take fall damage if its too high to encourage players to actually get in position.

**Comment by Cazsius** [comment]
Please add suggestions to the discord channel linked below:
https://discord.gg/VkXWtPD
