### ISSUE TITLE
Autoregenerating leaves/ edibale leaves

### ISSUE THREAD

**Issue by yoloarf** [JurassiCraftTeam/JurassiCraft2#377]
I now know thanks to a commenter that the leaves are being eaten 
When a leave is broken/eaten from a jurrasicraft tree it will after a few days regen.

**Comment by PT400C** [comment]
Dinosaurs do actually eat leaves from trees and destroy the blocks, but I'm not sure if they regenerate.

**Comment by Cazsius** [comment]
Please add suggestions to the discord channel linked below:
https://discord.gg/VkXWtPD
