### ISSUE TITLE
REQUEST: Abandoned Ingen Worker Village

### ISSUE THREAD

**Issue by DeinoRaptor** [JurassiCraftTeam/JurassiCraft2#380]
The only way I can request something like this if I post it here, but I have a little request that would actually make sense in the Jurassicraft mod.

So if you know, The Lost World: Jurassic Park had a scene near the end where the main group was in the Village, which was abandoned. Its main reason was to house Ingen Workers, but my idea is that it would be a structure in the mod itself, abandoned. It I think contains 3 buildings, the Boarding House, the Gas Station, and the Communication Center, and I think that is what it is called.

So it would be cool if I saw it in the mod, but actually, I can build the structure and send it to the team.

**Comment by Cazsius** [comment]
Please add suggestions to the discord channel linked below:
https://discord.gg/VkXWtPD
