### ISSUE TITLE
Feeder glitch

### ISSUE THREAD

**Issue by 8BitTryston** [JurassiCraftTeam/JurassiCraft2#383]
there is a glitch with the feeder it keeps opening and closing really fast like spaming and my t-rex is at full bar of food.

EDIT:

That glitch seems to be only triggering the sound of the feeder. Probably the lid opens too - slightly, but that needs further investigation.

**Comment by Shrek5InTheatres2019** [comment]
can you provide any evidence of this happening? screen recording maybe?

**Comment by Cazsius** [comment]
Has this happened more than once? Does this randomly occur? Were you doing anything specific when you saw this happening?

**Comment by PT400C** [comment]
Should be fixed with the upcoming release.
