### ISSUE TITLE
Leaves not decaying on JC Trees

### ISSUE THREAD

**Issue by Gothic-Lycan** [JurassiCraftTeam/JurassiCraft2#384]
Seems that leaves from JC mod trees are not decaying when too far from nearby log blocks.

**Comment by CraftedMods** [comment]
I just looked at the code, and saw that the decay mechanism isn't supported currently (https://github.com/JurassiCraftTeam/JurassiCraft2/blob/3de6d35d0824626dfd2afa01e835781570b4c83f/src/main/java/org/jurassicraft/server/block/tree/AncientLeavesBlock.java#L40).

**Comment by CraftedMods** [comment]
We've to adjust the decay mechanism, because with the default decaying properties some trees will partially self-destruct, because for some models the leaves are too far away from the wooden parts of the tree.
