### ISSUE TITLE
Too Many Bugs From grass blocks

### ISSUE THREAD

**Issue by MokahTGS** [JurassiCraftTeam/JurassiCraft2#386]
There needs to either be a way to turn off or configure the drop rate of bugs from dirt.  Chests are filling up with basically useless crickets.  Can we please get a fix for this?

**Comment by PT400C** [comment]
Quick fix: Throw them away.

**Comment by MokahTGS** [comment]
why are they even there?

**Comment by NeusFear** [comment]
They feed microraptors and in the future other small dinos

**Comment by Cazsius** [comment]
This has been fixed in the latest dev build will be released soon.
