### ISSUE TITLE
Goat Pathfinding

### ISSUE THREAD

**Issue by NeusFear** [JurassiCraftTeam/JurassiCraft2#388]
Goats (at least) cant pathfind though Jurassicraft doors
may have to test other dinos

**Comment by CraftedMods** [comment]
I assume you used the latest version, `1.12.2-2.1.14`. I did some testing, and came to the following results:
* If I'm holding wheat in my hands and am trying to lure a goat through a door, it won't work. Not only with the JC doors, but also with vanilla doors. So I tested it with cows, and came to the same results.
* If I mated two goats and separated the child from it's parents (with a door between them), the child walked through the opened doors to it's parents, but also not always.
Then I looked the the Mc bug tracker, and found this one, which got resolved at 1.13: https://bugs.mojang.com/browse/MC-102896?jql=status%20%3D%20Resolved%20AND%20text%20~%20%22pathfinding%20door%22

**Comment by PT400C** [comment]
Closed as it's an actual MC problem.
