### ISSUE TITLE
my dinosaurs are turning invisible

### ISSUE THREAD

**Issue by Slipperydane** [JurassiCraftTeam/JurassiCraft2#396]
first my parasauraphos turned invisible then went un invisible then my raptors.then i tried what i could to fix it but i couldn't this is in the newest update

**Comment by PT400C** [comment]
Did that happen on the official server or in a singleplayer world? Do you have got any logs which probably contain errors?

**Comment by Slipperydane** [comment]
no missing logs just the dinosaurs and its the single player.whats the official server

**Comment by PT400C** [comment]
I would like to contact you via discord to ask further questions. What's your discord name + discriminator?

**Comment by Slipperydane** [comment]
sorry i was gone so long but any ways i don't have a discord but i will download

**Comment by Slipperydane** [comment]
slipperydane is my username and it says #8637 under the username

**Comment by PT400C** [comment]
So, as I'm not able to reproduce that bug, I'll close the issue now.
