### ISSUE TITLE
Compile fails , issue with Junit platform

### ISSUE THREAD

**Issue by Tsoccerguy3** [JurassiCraftTeam/JurassiCraft2#403]
May be related to problems others are having with new versions Junit platform

Build file '/Dev/jc2/build.gradle' line: 104

* What went wrong:
A problem occurred evaluating root project 'JurassiCraft'.
> Could not find method useJUnitPlatform() for arguments [] on task ':test' of type org.gradle.api.tasks.testing.Test.

Compiling from Terminal in Linux Mint 19 and Windows 10 x64 fails

**Comment by Tsoccerguy3** [comment]
I had to delete these lines in build.gradle to compile
` test {
 useJUnitPlatform()
/*
  useJUnitPlatform {
    includeTags 'fast', 'smoke & feature-a'
//  excludeTags 'slow', 'ci'
    includeEngines 'junit-jupiter'
//  excludeEngines 'junit-vintage'
  }
*/
}`

**Comment by PT400C** [comment]
Closed as there was no further investigation/progress on that issue.
