### ISSUE TITLE
Dinosaurs Not Spawning

### ISSUE THREAD

**Issue by DoveGirl777** [JurassiCraftTeam/JurassiCraft2#407]

**Comment by CraftedMods** [comment]
Your logs aren't readable for us. Probably something with the encodings went wrong. Could you edit your post with the actual readable logs?

**Comment by DoveGirl777** [comment]
I can't post a readble log because it freezes my page. Can I close this and open another issue so i can post the logs?

**Comment by DoveGirl777** [comment]
i found the readable latest log

**Comment by CraftedMods** [comment]
You can post it via https://pastebin.com. Just post the link here.

**Comment by CraftedMods** [comment]
In case this issue is resolved for you, just let us know, so that we can close this.

**Comment by DoveGirl777** [comment]
THe issue is resolved you can close this now.
