### ISSUE TITLE
Raptors take damage when scrapping by walls or corners

### ISSUE THREAD

**Issue by TheCreeper23** [JurassiCraftTeam/JurassiCraft2#411]
Velociraptors will take immediate damage if less than half their body goes through a block.  I've seen this occur multiple times when spawning a pack of raptors into a village, though the effect is probably the same in any other situation, especially if it involves small man-made structures.

**Comment by PT400C** [comment]
This is a known bug and applies to mussaurs and other small dinosaurs as well.

**Comment by Canus8** [comment]
I remember the Fossils and Archeology mod giving a death message when a tamed dinosaur (or other creature) died, and it would also say how the creature died (drowning, sufficating, etc.).  I feel this would be helpful in this mod, too.  I have had mussaurus live just fine, but it was a world with cheats enabled.  Raptors have repeatedly died, and I do blame this bug for it (although, my most recent raptors, Hermione and Ronald, were simply released into the wild, with plenty of pigs and goats and water and they still appear to have died).

**Comment by PT400C** [comment]
A fix is on the way, also this is linked to #447
