### ISSUE TITLE
Fatal error message when sometimes using the ingen field guide item on a dinosaur

### ISSUE THREAD

**Issue by Xectarrr** [JurassiCraftTeam/JurassiCraft2#415]
Once or twice using the ingen field guide I've experienced a fatal error, kicking me from the server, of course I could immediately rejoin though.  Both instances occurred will I used the ingen field guide on a microraptor.

**Comment by Shrek5InTheatres2019** [comment]
Do you have a log from this event? We can't fix a bug without a log telling us what's wrong

**Comment by PT400C** [comment]
Assigning myself as I modified the field guide before.

**Comment by PT400C** [comment]
Closing the issue as it's related to a known bug which will be resolved with the next bug fixing release.
