### ISSUE TITLE
crash on startup color assignment

### ISSUE THREAD

**Issue by kuroyure** [JurassiCraftTeam/JurassiCraft2#418]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FMLPlugin (elulib-0.1.12.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  LoadingPlugin (Quark-r1.5-127.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.14.jar)
  LoadingPlugin (DimensionRules-MC1.12-1.1.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 8/25/18 10:27 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from JurassiCraft (jurassicraft)
Caused by: java.lang.IllegalArgumentException: Block must be registered before assigning color handler.
	at net.minecraft.client.renderer.color.ItemColors.func_186731_a(ItemColors.java:156)
	at org.jurassicraft.client.render.RenderingHandler.init(RenderingHandler.java:478)
	at org.jurassicraft.client.proxy.ClientProxy.onInit(ClientProxy.java:71)
	at org.jurassicraft.JurassiCraft.onInit(JurassiCraft.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1539247352 bytes (1467 MB) / 5411700736 bytes (5161 MB) up to 10021765120 bytes (9557 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10752m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2747 Optifine OptiFine_1.12.2_HD_U_D3 136 mods loaded, 136 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                   | Version                  | Source                                            | Signature                                |
	|:----- |:------------------------------------ |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft                            | 1.12.2                   | minecraft.jar                                     | None                                     |
	| UCHI  | mcp                                  | 9.42                     | minecraft.jar                                     | None                                     |
	| UCHI  | FML                                  | 8.0.99.99                | forge-1.12.2-14.23.4.2747.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                                | 14.23.4.2747             | forge-1.12.2-14.23.4.2747.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | elucore                              | 1.0                      | minecraft.jar                                     | None                                     |
	| UCHI  | movillages                           | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                        | None                                     |
	| UCHI  | infinitylib                          | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                            | None                                     |
	| UCHI  | agricraft                            | 2.12.0-1.12.0-a5         | agricraft-2.12.0-1.12.0-a5.jar                    | None                                     |
	| UCHI  | ambientsounds                        | 2.0.0                    | AmbientSounds_v2.3_mc1.12.2.jar                   | None                                     |
	| UCHI  | baubles                              | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| UCHI  | ctm                                  | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                         | None                                     |
	| UCHI  | chisel                               | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                      | None                                     |
	| UCHI  | jei                                  | 4.11.0.212               | jei_1.12.2-4.11.0.212.jar                         | None                                     |
	| UCHI  | mantle                               | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                          | None                                     |
	| UCHI  | twilightforest                       | 3.8.654                  | twilightforest-1.12.2-3.8.654-universal.jar       | None                                     |
	| UCHI  | tconstruct                           | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                   | None                                     |
	| UCHI  | extrautils2                          | 1.0                      | extrautils2-1.12-1.8.5.jar                        | None                                     |
	| UCHI  | flyringbaublemod                     | 0.3.1_1.12-d4e654e       | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar       | None                                     |
	| UCHI  | botania                              | r1.10-354                | Botania r1.10-354.jar                             | None                                     |
	| UCHI  | craftstudioapi                       | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar             | None                                     |
	| UCHI  | natura                               | 1.12.2-4.3.2.62          | natura-1.12.2-4.3.2.62.jar                        | None                                     |
	| UCHI  | harvestcraft                         | 1.12.2y                  | Pam's HarvestCraft 1.12.2y.jar                    | None                                     |
	| UCHI  | quark                                | r1.5-127                 | Quark-r1.5-127.jar                                | None                                     |
	| UCHI  | animania                             | 1.5.1.1                  | animania-1.12.2-1.5.1.1.jar                       | None                                     |
	| UCHI  | applecore                            | 3.1.4                    | AppleCore-mc1.12.2-3.1.4.jar                      | None                                     |
	| UCHI  | appleskin                            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| UCHI  | aroma1997core                        | 2.0.0.0                  | Aroma1997Core-1.12.2-2.0.0.0.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHI  | aroma1997sdimension                  | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar | None                                     |
	| UCHI  | autoreglib                           | 1.3-20                   | AutoRegLib-1.3-20.jar                             | None                                     |
	| UCHI  | backpack                             | 3.0.2                    | backpack-3.0.2-1.12.2.jar                         | None                                     |
	| UCHI  | ichunutil                            | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                        | None                                     |
	| UCHI  | backtools                            | 7.0.0                    | BackTools-1.12.2-7.0.0.jar                        | None                                     |
	| UCHI  | basemetals                           | 2.5.0-beta5              | BaseMetals-1.12-2.5.0-beta5.214.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI  | betterbedrockgen                     | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar             | None                                     |
	| UCHI  | betterbuilderswands                  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar   | None                                     |
	| UCHI  | betterfoliage                        | 2.1.10                   | BetterFoliage-MC1.12-2.1.10.jar                   | None                                     |
	| UCHI  | bibliocraft                          | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| UCHI  | blockcraftery                        | 0.1.3                    | blockcraftery-0.1.3.jar                           | None                                     |
	| UCHI  | blur                                 | 1.0.4-14                 | Blur-1.0.4-14.jar                                 | None                                     |
	| UCHI  | carryon                              | 1.10                     | Carry On MC1.12.2 v1.10.jar                       | None                                     |
	| UCHI  | chameleon                            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| UCHI  | classiccombat                        | 1.0.0                    | ClassicCombat-1.12-1.0.0.jar                      | None                                     |
	| UCHI  | redstoneflux                         | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI  | cofhcore                             | 4.5.3                    | CoFHCore-1.12.2-4.5.3.20-universal.jar            | None                                     |
	| UCHI  | crafttweaker                         | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
	| UCHI  | conarm                               | 1.0.2                    | conarm-1.12.2-1.0.2.jar                           | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHI  | cookingforblockheads                 | 6.4.44                   | CookingForBlockheads_1.12.2-6.4.44.jar            | None                                     |
	| UCHI  | cosmeticarmorreworked                | 1.12.2-v3                | CosmeticArmorReworked-1.12.2-v3.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHI  | tombmanygraves2api                   | 1.12.2-1.0.0             | tombmanygraves2api-1.12.2-1.0.0.jar               | None                                     |
	| UCHI  | tombmanygraves                       | 1.12-4.1.0               | TombManyGraves-1.12-4.1.0.jar                     | None                                     |
	| UCHI  | cosmeticarmorreworked|tombmanygraves | 1.12.2-v3                | CosmeticArmorReworked-1.12.2-v3.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHI  | ctgui                                | 1.0.0                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
	| UCHI  | crafttweakerjei                      | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
	| UCHI  | cucumber                             | 1.1.1                    | Cucumber-1.12.2-1.1.1.jar                         | None                                     |
	| UCHI  | custombackgrounds                    | 1.0                      | CustomBackgrounds-MC1.12-1.1.1.jar                | None                                     |
	| UCHI  | custommainmenu                       | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar                 | None                                     |
	| UCHI  | cyclicmagic                          | 1.16.10                  | Cyclic-1.12.2-1.16.10.jar                         | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| UCHI  | drpcore                              | 0.3.5.4                  | Dark Roleplay Core Alpha-0.3.5e.jar               | None                                     |
	| UCHI  | drpmedieval                          | 0.2.4.3                  | Dark Roleplay Medieval Alpha-0.2.4c.jar           | None                                     |
	| UCHI  | deathquotes                          | 1.2.0                    | DeathQuotes-1.2.0-mc1.12-forge.jar                | None                                     |
	| UCHI  | dimensionrules                       | 1.1                      | DimensionRules-MC1.12-1.1.jar                     | None                                     |
	| UCHI  | dirt2path                            | 1.7.1                    | dirt2path-1.8.0.jar                               | None                                     |
	| UCHI  | disenchanter                         | 1.6                      | disenchanter-[1.12]1.6.jar                        | None                                     |
	| UCHI  | doggytalents                         | 1.14.2.321               | Doggy Talents-1.12.2-1.14.2.321-universal.jar     | None                                     |
	| UCHI  | dungpipe                             | 1.0                      | Dung Pipe-1.2.jar                                 | None                                     |
	| UCHI  | dynamiclights                        | 1.4.9                    | DynamicLights-1.12.2.jar                          | None                                     |
	| UCHI  | dynamiclights_onfire                 | 1.0.7                    | DynamicLights-1.12.2.jar                          | None                                     |
	| UCHI  | dynamiclights_creepers               | 1.0.6                    | DynamicLights-1.12.2.jar                          | None                                     |
	| UCHI  | dynamiclights_dropitems              | 1.1.0                    | DynamicLights-1.12.2.jar                          | None                                     |
	| UCHI  | dynamiclights_entityclasses          | 1.0.1                    | DynamicLights-1.12.2.jar                          | None                                     |
	| UCHI  | dynamiclights_mobequipment           | 1.1.0                    | DynamicLights-1.12.2.jar                          | None                                     |
	| UCHI  | dynamiclights_flamearrows            | 1.0.1                    | DynamicLights-1.12.2.jar                          | None                                     |
	| UCHI  | dynamiclights_floodlights            | 1.0.3                    | DynamicLights-1.12.2.jar                          | None                                     |
	| UCHI  | dynamiclights_otherplayers           | 1.0.9                    | DynamicLights-1.12.2.jar                          | None                                     |
	| UCHI  | dynamiclights_theplayer              | 1.1.3                    | DynamicLights-1.12.2.jar                          | None                                     |
	| UCHI  | dsurround                            | 3.4.9.14                 | DynamicSurroundings-1.12.2-3.4.9.14.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHI  | presets                              | 3.4.9.14                 | DynamicSurroundings-1.12.2-3.4.9.14.jar           | None                                     |
	| UCHI  | embers                               | 0.230                    | embers-0.230.jar                                  | None                                     |
	| UCHI  | equaldragons                         | 1.1                      | EqualDragons-1.1.jar                              | None                                     |
	| UCHI  | familiarfauna                        | 1.0.10                   | FamiliarFauna-1.12.2-1.0.10.jar                   | None                                     |
	| UCHI  | farmingforblockheads                 | 3.1.21                   | FarmingForBlockheads_1.12.2-3.1.21.jar            | None                                     |
	| UCHI  | farseek                              | 2.3.1                    | Farseek-1.12-2.3.1.jar                            | None                                     |
	| UCHI  | fastleafdecay                        | v14                      | FastLeafDecay-v14.jar                             | None                                     |
	| UCHI  | friendlyfire                         | 1.5.8                    | FriendlyFire-1.12.2-1.5.8.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI  | waila                                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| UCHI  | llibrary                             | 1.7.15                   | llibrary-1.7.15-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHI  | iceandfire                           | 1.5.2                    | iceandfire-1.5.2.jar                              | None                                     |
	| UCHI  | inventorytweaks                      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHI  | ironchest                            | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                   | None                                     |
	| UCHI  | jehc                                 | 1.12.2                   | JEHC-1.12.2-1.6.1.0.jar                           | None                                     |
	| UCHI  | journeymap                           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| UCHI  | loottweaker                          | 0.0.7                    | LootTweaker-1.12.2-0.0.7.jar                      | None                                     |
	| UCHI  | jeresources                          | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar           | None                                     |
	| UCHI  | kleeslabs                            | 5.4.10                   | KleeSlabs_1.12.2-5.4.10.jar                       | None                                     |
	| UCHI  | launchgui                            | @VERSION@                | LaunchGui-1.9.4-2.0.3-24-client.jar               | None                                     |
	| UCHI  | minecolonies                         | 1.12.2-0.9.1-RELEASE     | minecolonies-1.12.2-0.9.1-RELEASE-universal.jar   | None                                     |
	| UCHI  | morelootstuff                        | 0.0.4                    | MoreLootStuff-1.12.2-0.0.4.jar                    | None                                     |
	| UCHI  | morpheus                             | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                           | None                                     |
	| UCHI  | mousetweaks                          | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                      | None                                     |
	| UCHI  | mycommands                           | 1.12.2-01                | MyCommands-1.12.2-01.jar                          | None                                     |
	| UCHI  | mysticalagriculture                  | 1.6.13                   | MysticalAgriculture-1.12-1.6.13.jar               | None                                     |
	| UCHI  | mysticalagradditions                 | 1.2.8                    | mysticalagradditions-1.12-1.2.8.jar               | None                                     |
	| UCHI  | nethermetals                         | 1.2.0-beta3              | NetherMetals-1.12-1.2.0-beta3.52.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI  | recipehandler                        | 0.11                     | NoMoreRecipeConflict-0.11(1.12.2).jar             | None                                     |
	| UCHI  | oreexcavation                        | 1.4.123                  | OreExcavation-1.4.123.jar                         | None                                     |
	| UCHI  | oeintegration                        | 2.3.3                    | oeintegration-2.3.3.jar                           | None                                     |
	| UCHI  | orespawn                             | 3.3.0                    | OreSpawn-1.12-3.3.0.136.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI  | outfox                               | 0.1.2                    | outfox-0.1.2-mc1.12.2.jar                         | None                                     |
	| UCHI  | plustic                              | 6.5.2.0                  | plustic-6.5.2.0.jar                               | None                                     |
	| UCHI  | primitivemobs                        | 1.1.6                    | primitivemobs-1.1.6_beta.jar                      | None                                     |
	| UCHI  | realdrops                            | 1.2.12                   | RealisticItemDrops-1.2.12.jar                     | None                                     |
	| UCHI  | realrender                           | 1.2.3                    | realrender-1.2.3.jar                              | None                                     |
	| UCHI  | reforged                             | 0.7.5                    | Reforged-0.7.5-1.12+.jar                          | None                                     |
	| UCHI  | resourceloader                       | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHI  | rustic                               | 1.0.8                    | rustic-1.0.8.jar                                  | None                                     |
	| UCHI  | simpledimensions                     | 1.3.1                    | SimpleDimensions-MC1.12-1.3.1.jar                 | None                                     |
	| UCHI  | spartanshields                       | 1.4.1                    | SpartanShields-1.12.2-1.4.1.jar                   | None                                     |
	| UCHI  | stg                                  | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                              | None                                     |
	| UCHI  | storagedrawers                       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                   | None                                     |
	| UCHI  | storagedrawersextra                  | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar               | None                                     |
	| UCHI  | streams                              | 0.4.4                    | Streams-1.12-0.4.4.jar                            | None                                     |
	| UCHI  | tinkersaddons                        | 1.0.7                    | Tinkers' Addons-1.12.1-1.0.7.jar                  | None                                     |
	| UCHI  | tcomplement                          | ${version}               | TinkersComplement-1.12.2-0.2.3b.jar               | None                                     |
	| UCHI  | tinkertoolleveling                   | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar               | None                                     |
	| UCHI  | tp                                   | 3.2.29                   | tinyprogressions-1.12.2-3.3.29-Release.jar        | None                                     |
	| UCHI  | tombmanypluginscosmeticarmorreworked | 1.0.0                    | tombmanypluginscosmeticarmorreworked-1.0.0.jar    | None                                     |
	| UCHI  | treegrowingsimulator                 | 0.0.4                    | TreeGrowingSimulator2017-1.0.1.jar                | None                                     |
	| UCHI  | unlimitedchiselworks                 | 0.2.0                    | UnlimitedChiselWorks-0.2.0.jar                    | None                                     |
	| UCHI  | wailaharvestability                  | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar             | None                                     |
	| UCHI  | waystones                            | 4.0.54                   | Waystones_1.12.2-4.0.54.jar                       | None                                     |
	| UCHI  | wearables                            | 1.1.3                    | wearables-1.1.3.jar                               | None                                     |
	| UCHI  | wolfarmor                            | 2.2.3.6                  | wolfarmor-1.12.2-2.2.3.1798-universal.jar         | None                                     |
	| UCHI  | immersiveengineering                 | 0.12-84                  | ImmersiveEngineering-0.12-84.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHEE | jurassicraft                         | 2.1.16                   | JurassiCraft-1.12.2-2.1.16.jar                    | None                                     |
	| UCH   | reauth                               | 3.6.0                    | reauth-3.6.0.jar                                  | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| UCH   | elulib                               | 0.1.12                   | elulib-0.1.12.jar                                 | None                                     |

	Loaded coremods (and transformers): 
FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  farseek.core.FarseekClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Quark-r1.5-127.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.14.jar)
  org.blockartistry.DynSurround.asm.Transformer
LoadingPlugin (DimensionRules-MC1.12-1.1.jar)
  lumien.dimensionrules.asm.ClassTransformer
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Shrek5InTheatres2019** [comment]
I experienced the bug myself a while ago, and thought I had fixed it, turns out there was another pesky line causing the problem :/

**Comment by kuroyure** [comment]
Downgrading to the update that came by july25 solves it

**Comment by PT400C** [comment]
Yep, With the build after that one we introduced a problem with the rail blocks. This should be fixed with the next update.
