### ISSUE TITLE
Unresponsive Dinosaurs in Creative Mode

### ISSUE THREAD

**Issue by Taraxis** [JurassiCraftTeam/JurassiCraft2#422]
Version: 2.1.1.6

When hit/attacked by other dinos they seem to respond by rotating in place, but otherwise do not move from their spawn point. They will also lay down/do their default swaying motion. Seems to only affect certain dinosaurs.

Each image was taken almost 10 minutes apart, notice in the mountain screenshots that the micros/velos were moving, but the Rexes and Brachi were still in the same place
![download 1](https://user-images.githubusercontent.com/42722436/44632841-fdc72f00-a94f-11e8-9288-10d6804ff9dd.png)
![download](https://user-images.githubusercontent.com/42722436/44632842-fdc72f00-a94f-11e8-8f3c-e2b5cd30045a.png)
![download 2](https://user-images.githubusercontent.com/42722436/44632902-0e2bd980-a951-11e8-9305-2524291cf97e.png)
![image0 1](https://user-images.githubusercontent.com/42722436/44632844-fe5fc580-a94f-11e8-9c3c-3735e3d4415c.jpg)
![image0 2](https://user-images.githubusercontent.com/42722436/44632893-e63c7600-a950-11e8-9050-f191cb25d74d.jpg)

**Comment by PT400C** [comment]
I can't reproduce that in any way. Dinosaurs are walking around all the time and respond to damage they get as they are supposed to do.

**Comment by Taraxis** [comment]
It seemed to happen after I spawned a lot of dinosaurs, atleast 30 or so. The rexes moved around slightly at first, then stayed in place the rest of the time. However the brachi stayed in place since the start.

**Comment by PT400C** [comment]
@Taraxis It should be mentioned that pathfinding for the dinosaurs is a little more complex than for other minecraft mobs. As I tested it with my computer setup everything works as it should do. It seems that you play Minecraft on a laptop. Could send it's specs in here? Probably your CPU isn't able to keep up with generating the paths for the dinosaurs.

**Comment by TheMysteriousGray** [comment]
I have a pretty decent gaming PC (AMD FX-8350 eight-core with 8 GB of RAM) and the pathing sometimes screws up for me too. The T-rex will move around for a bit after being spawned, then stop dead in her tracks and stare directly east, growling occasionally but doing nothing else. If I attack her she runs away like normal, if I put a pig out she'll kill it, but she always goes back to staring east.

**Comment by Cazsius** [comment]
This is old, I am going to close unless the issue persists.
