### ISSUE TITLE
Bred animals not producing offspring in claimed areas [JC Official Server]

### ISSUE THREAD

**Issue by Xectarrr** [JurassiCraftTeam/JurassiCraft2#423]
I've been having trouble breeding animals in claimed areas, which has prevented me from protecting my livestock from trolls and so fourth as well as working small contraptions, and it starting to bother me, the only thing I receive from breeding in claimed areas is exp, which is not what I breed for, thank you.

-Xectarr

**Comment by NeusFear** [comment]
The GitHub is an area for bringing up issues about the mod itself, however if you're in need of server support you can join our discord if you haven't already at http://jurassicraftmod.com/discord and ask in the #support channel.

**Comment by Cazsius** [comment]
This is 100% open to server issues. No need to close this.

**Comment by Taraxis** [comment]
I can second this issue, have a variety of dinos over a 100 days old that have yet to breed.

**Comment by Xectarrr** [comment]
Hey Taraxis, I meant vanilla animals (cows, sheep, pigs) not dinosaurs.  And I've had breeding of my dinosaurs in claimed areas.
