### ISSUE TITLE
Action figures - Gender not applied on serverside

### ISSUE THREAD

**Issue by StarWarsDinosaur** [JurassiCraftTeam/JurassiCraft2#425]
On servers when you place female brachiosaurus they are just male.

**Comment by CraftedMods** [comment]
I can confirm this. Clientside the action figures work as expected, but as soon as I use a separate server, the gender property seems to be ignored. I also reproduced that for other action figures. Probably the error lies at the networking code. I'll take a look at it.

**Comment by PT400C** [comment]
This will be fixed with a further release. Here's the [link](https://github.com/JurassiCraftTeam/JurassiCraft2/pull/426) to the fix for quick reference.
