### ISSUE TITLE
Some dinosaurs are not rendering correctly in mob spawners

### ISSUE THREAD

**Issue by jredfox** [JurassiCraftTeam/JurassiCraft2#427]
modlist: llibrary-1.7.15-1.12.2,and JurassiCraft-1.12.2-2.1.17,aether_legacy-1.12.2-v3.2
Issue: mobs renders sideways in the spawner
CMD: `/give @p mob_spawner 1 0 {BlockEntityTag:{SpawnData:{id:"jurassicraft:entities.dilophosaurus"},Delay:10000}}`

issue is reproducible with and without (silkspawners & evil notch lib[coremods])
![2018-08-29_13 43 54](https://user-images.githubusercontent.com/9736369/44808372-ad3f1400-ab91-11e8-9c89-4a3ec6c16dc9.png)

**Comment by Shrek5InTheatres2019** [comment]
Are you able to provide screenshots of this occurrence?

**Comment by jredfox** [comment]
hold up

**Comment by jredfox** [comment]
there

**Comment by CraftedMods** [comment]
Does this only apply for JC mobs or also for any other mobs?

**Comment by jredfox** [comment]
only jc from what I can tell

**Comment by CraftedMods** [comment]
Can you post the command with which you create the spawner?

**Comment by jredfox** [comment]
/give @p mob_spawner 1 0 {BlockEntityTag:{SpawnData:{id:jurassicraft:entities.dilophosaurus},Delay:10000 }}

**Comment by jredfox** [comment]
even the dinos that render up sometimes twist back down sidways-ish more then it should

**Comment by PT400C** [comment]
This bug will be fixed with a later bug fixing release. Here's the current fix for reference: [Link](https://github.com/JurassiCraftTeam/JurassiCraft2/pull/431)
