### ISSUE TITLE
Potential bug, moss is not destroyed by water

### ISSUE THREAD

**Issue by Xectarrr** [JurassiCraftTeam/JurassiCraft2#433]
Currently, moss is not destroyed by water, which prevents some water using farm designs. I'm not 100% sure if this is a bug, but I've placed it here as a bug anyways.

-Xectarr

**Comment by PT400C** [comment]
@Xectarrr We came to the conclusion that moss in reallife is most likely to resist any kind of overflow of water. There are even some kinds of moss which live under-water all the time. So, the moss won't be destroyable by water in the future. I'm sorry, to destroy that kind of farm but it's our approach of keeping the mod as near as possible to the reallife ;)
