### ISSUE TITLE
Trex spin problem back from 2.0.5

### ISSUE THREAD

**Issue by StarWarsDinosaur** [JurassiCraftTeam/JurassiCraft2#435]
![2018-08-31_21 23 49](https://user-images.githubusercontent.com/40134493/44941030-5dfd0d00-ad64-11e8-81ae-cca7a17cfcd7.png)

**Comment by PT400C** [comment]
@StarWarsDinosaur I don't get what you want to tell us by that screenshot. Could you explain that "Trex spin problem" any further and clarify what you mean?

**Comment by StarWarsDinosaur** [comment]
Sorry thought the devs what have remembered.

**Comment by StarWarsDinosaur** [comment]
The dinosaurs get caught in a spinning animation and it looks as if they are on rails spinning.

**Comment by PT400C** [comment]
So, that actually happens in various cases. Also, T. Rexes which are swimming in deep water have a problem with their path-finding. We'll investigate that further.
