### ISSUE TITLE
Idea for the Indominus Rex and Hybrids

### ISSUE THREAD

**Issue by Jeffpotato1** [JurassiCraftTeam/JurassiCraft2#438]
Maybe if you add the indominus rex you can add height difference because the indominus would be bigger then a Tyrannosaurus Rex and try adding hybrids that are with the current dinosaurs we can obtain. Love the mod keep the good work.

**Comment by Cazsius** [comment]
Please add suggestions to the discord channel linked below:
https://discord.gg/VkXWtPD
