### ISSUE TITLE
Para eye Texture glitched.

### ISSUE THREAD

**Issue by StarWarsDinosaur** [JurassiCraftTeam/JurassiCraft2#440]
![2018-09-02_17 19 07](https://user-images.githubusercontent.com/40134493/44960834-6e33fa00-aed4-11e8-8cbe-58661507b488.png)

**Comment by StarWarsDinosaur** [comment]
It’s the latest

**Comment by PT400C** [comment]
Does that happen without a shader as well?

**Comment by PT400C** [comment]
@StarWarsDinosaur Could you support us there?

**Comment by StarWarsDinosaur** [comment]
Yes I was using shaders idk about with out

**Comment by CraftedMods** [comment]
You should try it then without.

**Comment by PT400C** [comment]
I tried to replicate your situation with various shaders (Chocapic, SEUS, Apex etc.) and it seems to never happen. Please link your shader pack.

**Comment by PT400C** [comment]
As there was no further help from the reporter, this issue is closed now.
