### ISSUE TITLE
Spawn Eggs won't switch Gender

### ISSUE THREAD

**Issue by TheMysteriousGray** [JurassiCraftTeam/JurassiCraft2#441]
The spawn eggs for dinosaurs in Creative Mode are locked to spawning random genders. I've tried right-clicking in the air, SHIFT+right-click in air, CTRL+right-click in air, nothing.

**Comment by CraftedMods** [comment]
Which JC version do you use?

**Comment by CraftedMods** [comment]
I cannot confirm that with the latest Jc version, for me it works in singleplayer and multiplayer. I've to sneak and right-click the spawnegg in the air. Please check whether you're really using `SHIFT` as the sneaking-key.

**Comment by TheMysteriousGray** [comment]
It's been like this for every version since 2.1.7 that I've tried. The eggs spawn dinosaurs, but they do not change genders and will always spawn a random one. SHIFT is my crouch key.
