### ISSUE TITLE
1.8.8 JurassiCraft Texture Issue

### ISSUE THREAD

**Issue by ELMP123** [JurassiCraftTeam/JurassiCraft2#445]
I was playing jurassiCraft on 1.8.8 on so many of the blocks and items don't have textures. But when I google the mod, I see that there are textures for these items. Don't know what going on.
<img width="2560" alt="screen shot 2018-09-06 at 4 55 57 pm" src="https://user-images.githubusercontent.com/43049131/45184745-e7459100-b1f5-11e8-97d5-a242d7be6665.png">
<img width="2560" alt="screen shot 2018-09-06 at 4 55 08 pm" src="https://user-images.githubusercontent.com/43049131/45184777-fcbabb00-b1f5-11e8-886f-b71efec393f1.png">
<img width="2560" alt="screen shot 2018-09-06 at 4 56 12 pm" src="https://user-images.githubusercontent.com/43049131/45184809-15c36c00-b1f6-11e8-89c9-d3a314cafa21.png">
<img width="2560" alt="screen shot 2018-09-06 at 4 56 06 pm" src="https://user-images.githubusercontent.com/43049131/45184818-1f4cd400-b1f6-11e8-8d9a-be066ea59863.png">

**Comment by PT400C** [comment]
The world develops with years going into the past and so did the mod.
As it's almost three years after that 1.8.8 version has been released, it's certain that many features and textures weren't implemented at that time. We added them later but those changes only were in the builds for later MC versions and were not backported anymore.
