### ISSUE TITLE
Dinosaur teleportation when not near them.

### ISSUE THREAD

**Issue by StarWarsDinosaur** [JurassiCraftTeam/JurassiCraft2#447]
When I left the server and came back my dinosaurs teleported through the wall.
![2018-09-09_20 52 02](https://user-images.githubusercontent.com/40134493/45271103-592a0e80-b472-11e8-8d0c-c1f70441acc7.png)

**Comment by PT400C** [comment]
That's actually a bad problem. I sometimes encountered that too. It seems to be a problem of our AI and it's pathfinding while chunks are loading.

**Comment by PT400C** [comment]
@StarWarsDinosaur A potential fix is on the way... 9 months later lol
