### ISSUE TITLE
Tyrannosaurus Rex Kingdom Sign Visual Glitch

### ISSUE THREAD

**Issue by Xectarrr** [JurassiCraftTeam/JurassiCraft2#453]
After placing down the tyrannosaurus rex kingdom sign I noticed a section of the sign was black, but I could see the texturing underneath it, I'm not exactly sure what this is, as I did some testing to see if it was something to do with the lighting but it appears not.  So if you could fix it, that'd be great, thank you.

-Xectarr

**Comment by PT400C** [comment]
Due to the missing dynamic lighting-update, it was possible that this issue could happen. With the next release it should be resolved.
