### ISSUE TITLE
Compatability issue with Natural Fauna Mod (ZAWA AddOn)

### ISSUE THREAD

**Issue by TheCaptain13** [JurassiCraftTeam/JurassiCraft2#454]
[crash-2018-09-16_06.20.56-server.txt](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2386341/crash-2018-09-16_06.20.56-server.txt)

**Comment by TheCaptain13** [comment]
CTD on loading and creating worlds

**Comment by PT400C** [comment]
That's related to a problem with ZAWA, nothing JC causes.

**Comment by JoelZBub** [comment]
More specifically, the problem is related to Natural Fauna:a ZAWA Addon, which hasn't updated to be compatible with ZAWA and its new library. Use ZAWA 1.3.2 or uninstall Natural Fauna.
