### ISSUE TITLE
OP Dinosaurs, mod compatibility and riding

### ISSUE THREAD

**Issue by Feranogame** [JurassiCraftTeam/JurassiCraft2#463]
Okay so first: OP dinosaurs. For example, I just spawned six velociraptors. I spawned an Ice and Fire dragon. The dragon was killed without damaging the velociraptors, Tyranosaurus isn't turned into stone by the Gorgon (ice and fire), I think other dinosaurs also don't turn into stone, if you ever fix that next thing: Riding (something that JP raptors are good for). Dinosaur riding are a thing that would be really cool. I will just add a list to how I think riding should be:
-Triceratops: if you are the owner just put a triceratops saddle in it and ride it.
-Velociraptor: for it you should have and new type of taking: you should shift go to it (in adult form) and you should use a whip in it if it bite you. If not you should give it meat. After some time it would be tamed and you should be able to put a velociraptor saddle in it.
-Tyranosaurus: its taking would be like velociraptor's but with much more bites and it would be tamed when a juvenile. When an adult and tamed (tamed when it was a juvenile) you could put a Tyranosaurus saddle in it.
Ok I have no other ideas, maybe I will add more.

**Comment by PT400C** [comment]
Relating the first point: As this problem is related to the Ice and Fire mod, please report it [here](https://github.com/Alex-the-666/Ice_and_Fire/issues) so that the creators of that mod could resolve it.

**Comment by Feranogame** [comment]
No it isn't, it is just an example of how OP the dinosaurs are.

**Comment by Feranogame** [comment]
And the lack of mod compatibility

**Comment by PT400C** [comment]
With the next update, JC dinosaurs should be turned properly into stone by the Gorgon.
