### ISSUE TITLE
Plant Fossil Spawn [Sponge incompatibility]

### ISSUE THREAD

**Issue by Xectarrr** [JurassiCraftTeam/JurassiCraft2#465]
After some testing I have discovered that the plant fossil ore does not spawn in coal veins in worlds, except in abandoned visitor center structure, it would be wonderful if this could be fixed within the next update.

-Xectarr

**Comment by PT400C** [comment]
- That's a problem with the server software "Sponge Forge". We're in contact with the developers and try to resolve the problem.

**Comment by PT400C** [comment]
So, the bug will be resolved by the Sponge developers themselves. Within the next days, there should be a new release which fixes that bug.
