### ISSUE TITLE
Skeletons dissapear when Lucraft mod is installed

### ISSUE THREAD

**Issue by Kregoras** [JurassiCraftTeam/JurassiCraft2#471]
It seems to be some kind of incompatibility.

When you have both, Lucraft and JurassiCraft the skeletons display dissapear. The skeleton item is there, but the skeleton is not rendered on screen.

Steps to reproduce:
- Fresh install with last version of JurassiCraft + llibrary + Lucraft
- Enter creative or create a skeleton on table
- Place skeleton (Nothing appears but, according to wawla if you install it as well the item is there and can be destroyed)
- Removing Lucraft allows the skeleton to reappear.

Lucraft link: [https://minecraft.curseforge.com/projects/lucraft-core](https://minecraft.curseforge.com/projects/lucraft-core)

**Comment by PT400C** [comment]
As it seems that's a bug on the side of Lucraft-Core. The mod doesn't render entities properly. I'll investigate that further.

**Comment by PT400C** [comment]
The bug has been reported to the developers of Lucraft-Core. They'll investigate that as soon as possible.
