### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Funchyy** [JurassiCraftTeam/JurassiCraft2#475]
[12:27:37] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 10/21/18 12:27 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1022)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1022)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: jurassicraft:entities.velociraptor (org.jurassicraft.server.entity.dinosaur.VelociraptorEntity)
	Entity ID: 51657
	Entity Name: Velociraptor
	Entity's Exact location: 2027.92, 66.50, 3756.37
	Entity's Block location: World: (2027,66,3756), Chunk: (at 11,4,12 in 126,234; contains blocks 2016,0,3744 to 2031,255,3759), Region: (3,7; contains chunks 96,224 to 127,255, blocks 1536,0,3584 to 2047,255,4095)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['_resetting'/52054, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 99, 99
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 15 total; [EntitySeagull['Seagull'/51712, l='MpServer', x=2080.46, y=70.65, z=3796.65], EntityAsianElephant['Asian Elephant'/51713, l='MpServer', x=2090.42, y=74.00, z=3794.67], GoatEntity['Goat'/51655, l='MpServer', x=2038.49, y=66.00, z=3755.00], EntityPlayerSP['_resetting'/52054, l='MpServer', x=8.50, y=65.00, z=8.50], GoatEntity['Goat'/51656, l='MpServer', x=2028.93, y=65.12, z=3752.30], EntityLatchedRenderer['unknown'/169, l='MpServer', x=8.50, y=65.00, z=8.50], DinosaurEntity{ Velociraptor, id=51657, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=0, prevAge=0, maxAge135000, ticksExisted=1, entityAge=0, isMale=false, growthSpeedOffset=0
    , food=84000 / 84000 (73500.0), water=84000 / 84000 (73500.0), digestingFood=0 / 3000, health=10.162942 / 10.162942
    , pos=BlockPos{x=2027, y=67, z=3756}, eyePos=(2027.522546420683, 66.89030346679316, 3756.4034320221085), eyeHeight=0.41539425, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=0.48540613, bb=box[2027.6194460327647, 66.5, 3756.0741549350514 -> 2028.104852163317, 67.023577272892, 3756.5595610656037] }, EntityMinecartChest['Minecart with Chest'/51728, l='MpServer', x=2085.50, y=44.06, z=3872.50], EntityClownFish['Clownfish'/51665, l='MpServer', x=2030.51, y=61.28, z=3836.05], EntityFish['entity.BlueFish.name'/51669, l='MpServer', x=2026.26, y=59.49, z=3856.85], MoCEntityPiranha['Piranha'/51736, l='MpServer', x=2104.50, y=62.31, z=3887.50], MoCEntityPiranha['Piranha'/51737, l='MpServer', x=2105.50, y=61.19, z=3887.50], EntitySockeyeSalmon['Sockeye Salmon'/51769, l='MpServer', x=2120.41, y=12.00, z=3866.85], MoCEntityAngelFish['AngelFish'/51738, l='MpServer', x=2102.24, y=61.64, z=3886.07], EntityRedKangaroo['Red Kangaroo'/51615, l='MpServer', x=2120.07, y=74.00, z=3772.45]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/169, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2931045488 bytes (2795 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 5 total; -Xms4096m -Xmx4096m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_C8 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                      | Source                                          | Signature                                |
	|:------ |:------------------- |:---------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2                       | minecraft.jar                                   | None                                     |
	| UCHIJA | mcp                 | 9.42                         | minecraft.jar                                   | None                                     |
	| UCHIJA | FML                 | 8.0.99.99                    | modpack.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge               | 14.23.5.2768                 | modpack.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | actuallyadditions   | 1.12.2-r143                  | ActuallyAdditions-1.12.2-r143.jar               | None                                     |
	| UCHIJA | biomesoplenty       | 7.0.1.2361                   | BiomesOPlenty-1.12.2-7.0.1.2361-universal.jar   | None                                     |
	| UCHIJA | craftstudioapi      | 1.0.0                        | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| UCHIJA | animania            | 1.5.1.1                      | animania-1.12.2-1.5.1.1.jar                     | None                                     |
	| UCHIJA | gorecore            | 1.12.2-0.4.5                 | avatarmod-a5.9.2-alpha-2.jar                    | None                                     |
	| UCHIJA | avatarmod           | unspecified                  | avatarmod-a5.9.2-alpha-2.jar                    | None                                     |
	| UCHIJA | betteranimalsplus   | 1.1.3                        | betteranimalsplus-1.1.3.jar                     | None                                     |
	| UCHIJA | guideapi            | 1.12-2.1.7-62                | Guide-API-1.12-2.1.7-62.jar                     | None                                     |
	| UCHIJA | bloodmagic          | 1.12.2-2.3.3-101             | BloodMagic-1.12.2-2.3.3-101 (1).jar             | None                                     |
	| UCHIJA | zawa                | 1.12.2-1.4.0                 | zawa+-+1.4.0+(1.12.2).jar                       | None                                     |
	| UCHIJA | bookworm            | 1.12.2-1.0.0                 | bookworm+-+1.0.0+(1.12.2).jar                   | None                                     |
	| UCHIJA | buildcraftlib       | 7.99.14                      | buildcraft-7.99.14.jar                          | None                                     |
	| UCHIJA | buildcraftcore      | 7.99.14                      | buildcraft-7.99.14.jar                          | None                                     |
	| UCHIJA | buildcraftbuilders  | 7.99.14                      | buildcraft-7.99.14.jar                          | None                                     |
	| UCHIJA | buildcraftenergy    | 7.99.14                      | buildcraft-7.99.14.jar                          | None                                     |
	| UCHIJA | buildcraftfactory   | 7.99.14                      | buildcraft-7.99.14.jar                          | None                                     |
	| UCHIJA | buildcraftrobotics  | 7.99.14                      | buildcraft-7.99.14.jar                          | None                                     |
	| UCHIJA | buildcraftsilicon   | 7.99.14                      | buildcraft-7.99.14.jar                          | None                                     |
	| UCHIJA | buildcrafttransport | 7.99.14                      | buildcraft-7.99.14.jar                          | None                                     |
	| UCHIJA | cxlibrary           | 1.6.1                        | cxlibrary-1.12.1-1.6.1.jar                      | None                                     |
	| UCHIJA | deextinction        | 0.0.1                        | deextinction-0.0.2.jar                          | None                                     |
	| UCHIJA | exoticbirds         | 1.0                          | Exotic-Birds-Mod-1.12.2.jar                     | None                                     |
	| UCHIJA | extrautils2         | 1.0                          | extrautils2-1.12-1.8.5.jar                      | None                                     |
	| UCHIJA | llibrary            | 1.7.15                       | llibrary-1.7.15-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJA | iceandfire          | 1.5.2                        | iceandfire-1.5.2.jar                            | None                                     |
	| UCHIJA | ichunutil           | 7.1.4                        | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCHIJA | ic2                 | 2.8.100-ex112                | Industrial-Craft-2-Mod-Experimental-1.12.2.jar  | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJA | inventorypets       | 1.5.3.1                      | inventorypets-1.12-1.5.3.1.jar                  | None                                     |
	| UCHIJA | inventorytweaks     | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | ironchest           | 1.12.2-7.0.52.837            | ironchest-1.12.2-7.0.52.837.jar                 | None                                     |
	| UCHIJA | jei                 | 4.7.8.92                     | jei_1.12.1-4.7.8.92.jar                         | None                                     |
	| UCHIJA | millenaire          | Millénaire 7.0.0             | millenaire-1.12.2-7.0.0.jar                     | None                                     |
	| UCHIJA | minecolonies        | 1.12.2-0.10.11-ALPHA         | minecolonies-1.12.2-0.10.11-ALPHA-universal.jar | None                                     |
	| UCHIJA | mocreatures         | 12.0.5                       | Mo-Creatures-Mod-1.12.2.jar                     | None                                     |
	| UCHIJA | morefurnaces        | 1.10.5                       | MoreFurnaces-1.12.2-1.10.6.jar                  | None                                     |
	| UCHIJA | portalgun           | 7.0.2                        | Portal-Gun-Mod-1.12.2.jar                       | None                                     |
	| UCHIJA | theoneprobe         | 1.4.24                       | theoneprobe-1.12-1.4.24.jar                     | None                                     |
	| UCHIJA | bspkrscore          | at_0.9                       | Treecapitator-1.12-at_0.9a.jar                  | None                                     |
	| UCHIJA | treecapitator       | at_0.9                       | Treecapitator-1.12-at_0.9a.jar                  | None                                     |
	| UCHIJA | twilightforest      | 3.8.654                      | twilightforest-1.12.2-3.8.654-universal.jar     | None                                     |
	| UCHIJA | worldedit           | 6.1.8                        | worldedit-forge-mc1.12-6.1.8-dist.jar           | None                                     |
	| UCHIJA | xaerominimap        | 1.13.9                       | Xaeros-Minimap-Fair-Play-1.12.jar               | None                                     |
	| UCHIJA | zoocraftdiscoveries | 1.0                          | Zoocraft-Discoveries-Mod-1.12.2.jar             | None                                     |
	| UCHIJA | jurassicraft        | 2.1.18                       | JurassiCraft-1.12.2-2.1.18.jar                  | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13541 Compatibility Profile Context 0' Renderer: 'AMD Radeon HD 8500M Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 8500M Series GL version 4.5.13541 Compatibility Profile Context 0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13541 Compatibility Profile Context 0
	OpenGlRenderer: AMD Radeon HD 8500M Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
[12:27:37] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Novac\AppData\Roaming\.technic\modpacks\jurassic-craft-funchy\crash-reports\crash-2018-10-21_12.27.36-client.txt

**Comment by PT400C** [comment]
@Funchyy Does this happen all the time? Also, could you contact me via Discord for further information? PT400C#8363

**Comment by Funchyy** [comment]
> @Funchyy Does this happen all the time? Also, could you contact me via Discord for further information? PT400C#8363
Yes always when I enter my friend's server, but nothing happens with him. I added you to the discord

**Comment by PT400C** [comment]
This has been resolved: It was an issue of mis-configuration.
