### ISSUE TITLE
it crashes when enable Override growth serum disable"=false config

### ISSUE THREAD

**Issue by utoc123** [JurassiCraftTeam/JurassiCraft2#480]
if i change that optiion to true, it doesnt' crash.

**Comment by Gamebrothers4** [comment]
Can't reproduce

**Comment by utoc123** [comment]
i'm checking

**Comment by utoc123** [comment]
---- Minecraft Crash Report ----
// I blame JurassiCraft Team, author of JurassiCraft.

Time: 2018-10-28 21:43:43 KST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from JurassiCraft (jurassicraft)
Caused by: java.lang.NullPointerException
    at org.jurassicraft.server.item.ItemHandler.init(ItemHandler.java:318)
    at org.jurassicraft.server.proxy.ServerProxy.onPreInit(ServerProxy.java:94)
    at org.jurassicraft.client.proxy.ClientProxy.onPreInit(ClientProxy.java:51)
    at org.jurassicraft.JurassiCraft.onPreInit(JurassiCraft.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3929)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 8.1 (amd64) version 6.3
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 748587400 bytes (713 MB) / 2874671104 bytes (2741 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2772 101 mods loaded, 101 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version                 | Source                                          | Signature                                |
       |:----- |:-------------------- |:----------------------- |:----------------------------------------------- |:---------------------------------------- |
       | UCH   | minecraft            | 1.12.2                  | minecraft.jar                                   | None                                     |
       | UCH   | mcp                  | 9.42                    | minecraft.jar                                   | None                                     |
       | UCH   | FML                  | 8.0.99.99               | forge-1.12.2-14.23.5.2772.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | forge                | 14.23.5.2772            | forge-1.12.2-14.23.5.2772.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | advancedrocketrycore | 1                       | minecraft.jar                                   | None                                     |
       | UCH   | foamfixcore          | 7.7.4                   | minecraft.jar                                   | None                                     |
       | UCH   | opencomputers|core   | 1.7.2.67                | minecraft.jar                                   | None                                     |
       | UCH   | randompatches        | 1.12.2-1.6.1.0          | randompatches-1.12.2-1.6.1.0.jar                | None                                     |
       | UCH   | gottagofast          | 1.1                     | gottagofast-1.1.jar                             | None                                     |
       | UCH   | securitycraft        | v1.8.9                  | [1.12.2] SecurityCraft v1.8.9.jar               | None                                     |
       | UCH   | forgeendertech       | 1.12.2-4.4.0.0          | ForgeEndertech-1.12.2-4.4.0.0-build.0180.jar    | None                                     |
       | UCH   | adpother             | 1.12.2-0.8.6.0          | AdPother-1.12.2-0.8.6.0-build.0194.jar          | None                                     |
       | UCH   | libvulpes            | 0.2.8.-39               | LibVulpes-1.12.2-0.2.8-39-universal.jar         | None                                     |
       | UCH   | advancedrocketry     | 1.4.1.-108              | AdvancedRocketry-1.12.2-1.4.1-108-universal.jar | None                                     |
       | UCH   | infinitylib          | 1.12.2-1.12.0           | infinitylib-1.12.0.jar                          | None                                     |
       | UCH   | agricraft            | 2.12.0-1.12.0-a6        | AgriCraft-2.12.0-1.12.0-a6.jar                  | None                                     |
       | UCH   | aiimprovements       | 0.0.1.3                 | AIImprovements-1.12-0.0.1b3.jar                 | None                                     |
       | UCH   | craftstudioapi       | 1.0.0                   | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
       | UCH   | harvestcraft         | 1.12.2z                 | Pam's HarvestCraft 1.12.2za.jar                 | None                                     |
       | UCH   | theoneprobe          | 1.4.25                  | theoneprobe-1.12-1.4.25.jar                     | None                                     |
       | UCH   | wumpleutil           | 2.12.6                  | wumpleutil-1.12.2-2.12.6.jar                    | 1e57901a90acd4a3a54295b6decff5397be51a31 |
       | UCH   | foodfunk             | 4.9.5                   | foodfunk-1.12.2-4.9.5.jar                       | 1e57901a90acd4a3a54295b6decff5397be51a31 |
       | UCH   | quark                | r1.5-130                | Quark-r1.5-130.jar                              | None                                     |
       | UCH   | animania             | 1.5.1.1                 | animania-1.12.2-1.5.1.1.jar                     | None                                     |
       | UCH   | applecore            | 3.1.4                   | AppleCore-mc1.12.2-3.1.4.jar                    | None                                     |
       | UCH   | jei                  | 4.13.1.220              | jei_1.12.2-4.13.1.220.jar                       | None                                     |
       | UCH   | appleskin            | 1.0.9                   | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
       | UCH   | architecturecraft    | @VERSION@               | architecturecraft-1.12-3.80.jar                 | None                                     |
       | UCH   | atomicscience        | 1.12.2-3.1.0.55         | Atomic-Science-1.12.2-3.1.0b55.jar              | None                                     |
       | UCH   | autoreglib           | 1.3-20                  | AutoRegLib-1.3-20.jar                           | None                                     |
       | UCH   | bdlib                | 1.14.3.12               | bdlib-1.14.3.12-mc1.12.2.jar                    | None                                     |
       | UCH   | betterbuilderswands  | 0.12.0                  | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar | None                                     |
       | UCH   | forgelin             | 1.7.4                   | Forgelin-1.7.4.jar                              | None                                     |
       | UCH   | betterrecords        | 1.12.2-1.5.8            | BetterRecords-1.12.2-1.5.8.jar                  | None                                     |
       | UCH   | bibliocraft          | 2.4.5                   | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
       | UCH   | toughasnails         | 3.1.0.129               | ToughAsNails-1.12.2-3.1.0.129-universal.jar     | None                                     |
       | UCH   | forestry             | 5.8.2.356               | forestry_1.12.2-5.8.2.356.jar                   | None                                     |
       | UCH   | binniecore           | 2.5.0.168               | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCH   | binniedesign         | 2.5.0.168               | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCH   | genetics             | 2.5.0.168               | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCH   | botany               | 2.5.0.168               | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCH   | extrabees            | 2.5.0.168               | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCH   | extratrees           | 2.5.0.168               | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCH   | bionisation3         | 1.0.6                   | Bionisation3-1.12.2-1.0.6.jar                   | None                                     |
       | UCH   | zawa                 | 1.12.2-1.4.0            | zawa - 1.4.0 (1.12.2).jar                       | None                                     |
       | UCH   | bookworm             | 1.12.2-1.0.0            | bookworm - 1.0.0 (1.12.2).jar                   | None                                     |
       | UCH   | ctm                  | MC1.12.2-0.3.2.20       | CTM-MC1.12.2-0.3.2.20.jar                       | None                                     |
       | UCH   | chisel               | MC1.12.2-0.2.1.35       | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
       | UCH   | chiselsandbits       | 14.26                   | chiselsandbits-14.26.jar                        | None                                     |
       | UCH   | clumps               | 3.1.1                   | Clumps-3.1.1.jar                                | None                                     |
       | UCH   | cookingforblockheads | 6.4.65                  | CookingForBlockheads_1.12.2-6.4.65.jar          | None                                     |
       | UCH   | ptrmodellib          | 1.0.3                   | PTRLib-1.0.3.jar                                | None                                     |
       | UCH   | props                | 2.6.2                   | Decocraft-2.6.2_1.12.2.jar                      | None                                     |
       | UCH   | discordsuite         | 2.2.4                   | DiscordSuite-2.2.4.jar                          | None                                     |
       | UCH   | dsurround            | 3.4.9.17                | DynamicSurroundings-1.12.2-3.4.9.17.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | UCH   | presets              | 3.4.9.17                | DynamicSurroundings-1.12.2-3.4.9.17.jar         | None                                     |
       | UCH   | exoticbirds          | 1.0                     | Exotic Birds 1.12.2-2.1.0.jar                   | None                                     |
       | UCH   | fastfurnace          | 1.1.1                   | FastFurnace-1.12.2-1.1.1.jar                    | None                                     |
       | UCH   | fastbench            | 1.5.3                   | FastWorkbench-1.12.2-1.5.3.jar                  | None                                     |
       | UCH   | foamfix              | 0.10.2-1.12.2           | foamfix-0.10.2-1.12.2.jar                       | None                                     |
       | UCH   | cfm                  | 5.15.0                  | furniture-5.15.0-1.12.2.jar                     | None                                     |
       | UCH   | redstoneflux         | 2.1.0                   | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCH   | gendustry            | 1.6.5.8                 | gendustry-1.6.5.8-mc1.12.2.jar                  | None                                     |
       | UCH   | immersiveengineering | 0.12-86                 | ImmersiveEngineering-0.12-86.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | UCH   | geolosys             | 2.1.2                   | Geolosys-1.12.2-2.1.2.jar                       | None                                     |
       | UCH   | gravestone           | 1.10.2                  | gravestone-1.10.2.jar                           | None                                     |
       | UCH   | growthcraft          | 4.0.4.100               | growthcraft-1.12.2-4.0.4.100.jar                | None                                     |
       | UCH   | growthcraft_apples   | 4.0.4.100               | growthcraft-1.12.2-4.0.4.100.jar                | None                                     |
       | UCH   | growthcraft_bamboo   | 4.0.4.100               | growthcraft-1.12.2-4.0.4.100.jar                | None                                     |
       | UCH   | growthcraft_cellar   | 4.0.4.100               | growthcraft-1.12.2-4.0.4.100.jar                | None                                     |
       | UCH   | growthcraft_bees     | 4.0.4.100               | growthcraft-1.12.2-4.0.4.100.jar                | None                                     |
       | UCH   | growthcraft_fishtrap | 4.0.4.100               | growthcraft-1.12.2-4.0.4.100.jar                | None                                     |
       | UCH   | growthcraft_grapes   | 4.0.4.100               | growthcraft-1.12.2-4.0.4.100.jar                | None                                     |
       | UCH   | growthcraft_hops     | 4.0.4.100               | growthcraft-1.12.2-4.0.4.100.jar                | None                                     |
       | UCH   | growthcraft_milk     | 4.0.4.100               | growthcraft-1.12.2-4.0.4.100.jar                | None                                     |
       | UCH   | growthcraft_rice     | 4.0.4.100               | growthcraft-1.12.2-4.0.4.100.jar                | None                                     |
       | UCH   | hatchery             | 2.1.4                   | hatchery-1.12.2-2.1.4.jar                       | None                                     |
       | UCH   | immersivepetroleum   | 1.1.9                   | immersivepetroleum-1.12.2-1.1.9.jar             | None                                     |
       | UCH   | trackapi             | 1.1                     | TrackAPI-1.1_1.12.jar                           | None                                     |
       | UCH   | immersiverailroading | 1.3.3                   | ImmersiveRailroading-1.3.3_1.12.jar             | None                                     |
       | UCH   | immersivetech        | 1.3.10                  | immersivetech-1.12-1.3.10.jar                   | None                                     |
       | UCH   | improvedbackpacks    | 1.12.2-1.3.0.0          | ImprovedBackpacks-1.12.2-1.3.0.0.jar            | None                                     |
       | UCH   | laggoggles           | FORGE-1.12.2-4.1        | LagGoggles-FORGE-1.12.2-4.1.jar                 | None                                     |
       | UCH   | mts                  | 11.2.1                  | Minecraft Transport Simulator-1.12.2-11.2.1.jar | None                                     |
       | UCH   | mtsofficialpack      | 6.0.0                   | MTS_Official_Pack_V07.jar                       | None                                     |
       | UCH   | mw                   | 1.11.7.7                | mw-1.11.7.7_mc1.12.2.jar                        | None                                     |
       | UCH   | netherportalfix      | 5.3.17                  | NetherPortalFix_1.12.1-5.3.17.jar               | None                                     |
       | UCH   | nutrition            | 3.5.0                   | Nutrition-1.12.2-3.5.0.jar                      | None                                     |
       | UCH   | opencomputers        | 1.7.2.67                | OpenComputers-MC1.12.2-1.7.2.67.jar             | None                                     |
       | UCH   | p455w0rdslib         | 2.0.35                  | p455w0rdslib-1.12-2.0.35.jar                    | None                                     |
       | UCH   | realistictorches     | 2.1.1                   | RealisticTorches-1.12.2-2.1.1.jar               | None                                     |
       | UCH   | sereneseasons        | 1.2.6                   | SereneSeasons-1.12.2-1.2.6-universal.jar        | None                                     |
       | UCH   | signpic              | 2.8.1                   | SignPicture-1.12.1-2.8.1-universal.jar          | None                                     |
       | UCH   | tanaddons            | 3.4.24                  | ToughExpansion-1.12-3.4.24.jar                  | None                                     |
       | UCH   | unloader             | 1.2.0                   | unloader-1.2.0.jar                              | None                                     |
       | UCH   | vanillafix           | 1.0.9-97                | VanillaFix-1.0.9-97.jar                         | None                                     |
       | UCH   | llibrary             | 1.7.15                  | llibrary-1.7.15-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | UCEE  | jurassicraft         | 2.1.18                  | JurassiCraft-1.12.2-2.1.18.jar                  | None                                     |
       | UC    | reauth               | 3.6.0                   | reauth-3.6.0.jar                                | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | UC    | adchimneys           | 1.12.2-3.3.11.0         | AdChimneys-1.12.2-3.3.11.0-build.0194.jar       | None                                     |
       | UC    | hungeroverhaul       | 1.12.2-1.3.3.jenkins148 | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar      | None                                     |
  Loaded coremods (and transformers): LoadingPlugin (AdPother-1.12.2-0.8.6.0-build.0194.jar)
                                        com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$FurnaceDouble
                                        com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$CoalGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.BetterWithMods$Furnace
                                        com.endertech.minecraft.mods.adpother.transformers.CookingForBlockheads$Oven
                                        com.endertech.minecraft.mods.adpother.transformers.EnderIO$StirlingGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.FloodLights$CarbonFloodlight
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveCraft$FurnaceTE
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityBlastFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityDieselGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.Mekanism$FuelwoodHeater
                                        com.endertech.minecraft.mods.adpother.transformers.MoreFurnaces$IronFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$InferiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$IntermediumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$PrudentiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SuperiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SupremiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$UltimateFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.RealisticTorches$BlockTorch
                                        com.endertech.minecraft.mods.adpother.transformers.RFTools$CoalGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.StevesCarts$ModuleCoal
                                        com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronAlloyFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.TinkersConstruct$HeatingStructure
                                        com.endertech.minecraft.mods.adpother.transformers.SimpleGrinder$CoalGrinder
                                        com.endertech.minecraft.mods.adpother.renders.AerometerRender
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockCaughtFire
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockUpdateTick
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockExploded
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$GetSkyColor
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$FurnaceFuelBurned
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$LavaTouchesWater
                                      ForgelinPlugin (Forgelin-1.7.4.jar)
                                        
                                      AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.1-108-universal.jar)
                                        zmaster587.advancedRocketry.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      SignPictureCorePlugin (SignPicture-1.12.1-2.8.1-universal.jar)
                                        com.kamesuta.mc.signpic.asm.SignPictureTransformer
                                      DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.17.jar)
                                        org.blockartistry.DynSurround.asm.Transformer
                                      CorePlugin (ForgeEndertech-1.12.2-4.4.0.0-build.0180.jar)
                                        
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      RandomPatches (randompatches-1.12.2-1.6.1.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      LoadingPlugin (AdChimneys-1.12.2-3.3.11.0-build.0194.jar)
                                        com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
                                      LoadingPlugin (Quark-r1.5-130.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      weaponlib (mw-1.11.7.7_mc1.12.2.jar)
                                        com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
                                      llibrary (llibrary-core-1.0.8-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      GottaGoFastLoader (gottagofast-1.1.jar)
                                        com.thiakil.gottagofast.coremod.GottaGoFastASMTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13476 Compatibility Profile Context 22.19.171.1024' Renderer: 'AMD Radeon R7 M265DX'
  List of loaded APIs: * AgriCraftAPI (1.0) from AgriCraft-2.12.0-1.12.0-a6.jar
                       * AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.4.jar
                       * Baubles|API (1.4.0.2) from ImprovedBackpacks-1.12.2-1.3.0.0.jar
                       * BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
                       * bnnwidget (1.0) from SignPicture-1.12.1-2.8.1-universal.jar
                       * Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
                       * ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
                       * ChiselsAndBitsAPI (14.25.0) from chiselsandbits-14.26.jar
                       * CSLib|API (1.0.1) from PTRLib-1.0.3.jar
                       * ctm-api (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
                       * ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
                       * ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
                       * ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
                       * ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
                       * ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.2.356.jar
                       * ForgeEndertechAPI (1.0) from ForgeEndertech-1.12.2-4.4.0.0-build.0180.jar
                       * gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
                       * HatcheryAPI (1.11.2R1.0.0) from hatchery-1.12.2-2.1.4.jar
                       * ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-86.jar
                       * ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-86.jar
                       * ImprovedBackpacks|API (1.2.0.3) from ImprovedBackpacks-1.12.2-1.3.0.0.jar
                       * JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.13.1.220.jar
                       * opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.35.jar
                       * QuarkAPI (2) from Quark-r1.5-130.jar
                       * redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
                       * SecurityCraftAPI (1.2.3) from [1.12.2] SecurityCraft v1.8.9.jar
                       * theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.25.jar
  Suspected Mods: JurassiCraft (jurassicraft)
  Launched Version: forge-14.23.5.2772
  LWJGL: 2.9.4
  OpenGL: AMD Radeon R7 M265DX GL version 4.5.13476 Compatibility Profile Context 22.19.171.1024, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: No
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: [1.10.2]Dramatic Skys [v1.7].zip (incompatible)
  Current Language: �쒓뎅�� (���쒕�援�)
  Profiler Position: N/A (disabled)
  CPU: 4x AMD A10-7400P Radeon R6, 10 Compute Cores 4C+6G

**Comment by utoc123** [comment]
i'm  searching what mod crashing with

**Comment by Gamebrothers4** [comment]
still the growth serum

**Comment by PT400C** [comment]
The next release will resolve this problem. ~Closed
