### ISSUE TITLE
Helicopter Despawn Issue

### ISSUE THREAD

**Issue by tux-in-blue** [JurassiCraftTeam/JurassiCraft2#483]
sitting in a helicopter and leaving a server will cause you to lose the helicopter.

**Comment by Shrek5InTheatres2019** [comment]
it's most likely because when you leave the server the chunk your in will still be loaded for a bit, where the helicopter will go to the ground and then eventually despawn????? idk tho, just a guess

**Comment by PT400C** [comment]
I exessively tested that behaviour but couldn't reproduce it.
