### ISSUE TITLE
Crash when joining world

### ISSUE THREAD

**Issue by djkid** [JurassiCraftTeam/JurassiCraft2#489]
Made a new world in creative. Flew around for a bit. Quit. Attempted to rejoin and crashed before the world could load. Possible mod conflict??

[crash-2018-11-18_09.56.28-client.txt](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2592940/crash-2018-11-18_09.56.28-client.txt)

**Comment by PT400C** [comment]
@djkid Are you able to join the world again or does it crash every time?

**Comment by PT400C** [comment]
Closed, as we'll improve the mechanic which caused the crash in the future.
