### ISSUE TITLE
Can't put syringes in Embryo Calcification Machine

### ISSUE THREAD

**Issue by vallllllz** [JurassiCraftTeam/JurassiCraft2#490]
Hello,

This is my first time using this mod so I'm kinda new. I tried to put a 100% DNA syringe with an egg into the machine and it will not go in. Any help with this would be great, thanks!

EDIT:
Okay so I should have mentioned the syringe I was trying for was the coelacanth, but after checking it turns out the version I'm playing has no coelacanth egg. I'm playing on the latest 1.12.2 update, this might be the problem.

**Comment by PT400C** [comment]
@vallllllz Hello, first of I have to apologize for the incredibly late answer. Your request got a little under the waves and I didn't see it until now. Actually that isn't an issue, the coelacanth has to be created with the [Cultivator](http://jurassicraftmod.wikia.com/wiki/Cultivator).

I hope that help you
PT400C
