### ISSUE TITLE
Startup crash (NPE / EntitySound)

### ISSUE THREAD

**Issue by BrisingrAerowing** [JurassiCraftTeam/JurassiCraft2#491]
[Crash Report](https://gist.github.com/BrisingrAerowing/cae14cb016f4cae82c446e19b1ffc2b3)

Happened on startup. I'm reloading the game to see if it happens again. May be a conflict with another one of my mods (I have some that modify the sound system, namely Dynamic Surroundings and Sound Filters).

EDIT: Happened again.

**Comment by BrisingrAerowing** [comment]
I tested without DS and SF, and still happened. I'll do some more tests to see what mod is breaking things. The odd thing is that it worked correctly in a similar setup (that had DS and SF), so I'll run a diff between the modlists and see what's different.

**Comment by PT400C** [comment]
@BrisingrAerowing Do you have discord? I would like to send you a modified JC version which contains a potential fix: PT400C#8363.

**Comment by BrisingrAerowing** [comment]
Yup. I have a discord. "Brisingr Aerowing#9548"

**Comment by BrisingrAerowing** [comment]
Still crashes.

**Comment by PT400C** [comment]
Could you send the error log? Also, could you accept my Discord friend request?

**Comment by BrisingrAerowing** [comment]
I found the mods that cause the error: Dungeon Tweaks and EvilNotchLib. I'll poke the dev of those about this.

**Comment by jredfox** [comment]
close this as invalid

**Comment by PT400C** [comment]
As this was a problem of LLibrary, this issue is closed by now.

**Comment by BrisingrAerowing** [comment]
Nope. Still get the crash with latest LLib, Dungeon Tweaks, and Forge.

[Crash Log](https://paste.dimdev.org/cewacagemu.mccrash)

**Comment by jredfox** [comment]
yeah this is still valid. It's something with their entities playing sounds by simply instantiating them rather then using what vanilla methods did.

**Comment by jredfox** [comment]
it seems to crash with just llib and jc
