### ISSUE TITLE
Velociraptor action figure does not render in the inventory

### ISSUE THREAD

**Issue by darthvader45** [JurassiCraftTeam/JurassiCraft2#495]
I have 2.1.18 of Jurassicraft and 1.7.15 of LLibrary, and while I played I noticed the velociraptor action figure wasn't rendering in the inventory.  No amount of reloading or otherwise would fix this problem.

A screenshot of the problem:

![2018-11-30_14 52 22](https://user-images.githubusercontent.com/2816420/49311660-ba7cdf00-f4af-11e8-89a4-14ee9f2fefe7.png)

**Comment by TheCaptain13** [comment]
Also having the same issue. Tested for mod conflict and couldnt get the Raptor figure to show up in the inventory.

**Comment by PT400C** [comment]
@TheCaptain13 @darthvader45 Are you two using the chiselsandbits mod?

**Comment by TheCaptain13** [comment]
I am yes. Is it incompatible? I thought I checked all my mods.

**Comment by PT400C** [comment]
Currently it seems to be incompatible. I'll investigate that further in the future.

**Comment by TheCaptain13** [comment]
Alright, thank you very much

**Comment by darthvader45** [comment]
Agreed, thank you.  Just one question: would it be the same with the LittleTiles mod?  It's similar, and yet not as laggy (Took half the RAM at heavy testing (31x31x4 block of creations).

**Comment by BrisingrAerowing** [comment]
I was wondering why those don't render. Interesting bug. The only reason I use C&B is for covering MCMP compatible cable, but I have a lot of those.

**Comment by darthvader45** [comment]
Indeed, this is an odd one.  Hopefully the incompatibility can be fixed.  For now, a workaround is to right-click the velociraptor figure once, to switch it to place a male velociraptor figure.  All three settings have the same icon (or are intended to), so it'll look fine.

**Comment by PT400C** [comment]
The problem will be fixed with the upcoming release. ~Closed
