### ISSUE TITLE
[Suggestion] Non-functional version of the breeding wand (T.Rex grabber toy), more toys

### ISSUE THREAD

**Issue by darthvader45** [JurassiCraftTeam/JurassiCraft2#496]
Noticed the breeding wand looked like that old T.Rex grabber toy.  Perhaps a non-functional variant with the same texture and a similar name to the one in the title?  On that note, I'd like to see more toys added, mainly for players who build stores to sell on the shelves.

**Comment by Cazsius** [comment]
https://github.com/JurassiCraftTeam/JurassiCraft2/issues
