### ISSUE TITLE
Crash When Instantiating Entity Tries to Play sound

### ISSUE THREAD

**Issue by jredfox** [JurassiCraftTeam/JurassiCraft2#497]
Crash:
https://pastebin.com/h07XKvyS
Cache:
https://github.com/jredfox/evilnotchlib/blob/master/src/main/java/com/evilnotch/lib/minecraft/util/EntityUtil.java#L842
FakeWorld:https://github.com/jredfox/evilnotchlib/blob/master/src/main/java/com/evilnotch/lib/minecraft/content/world/FakeWorld.java

Normally I am able to try and catch all exceptions when creating entities for silkspawners/dungeon tweaks. But, one of your own is trying to play a sound and it's crashing by another method not throwing an exception but, simply if one occurs force a crash instead so I can't catch it.

My library goes through all entities and tries to cache stuff like resource locations to entity colors for silkspawners. What is a living and non living entity stuff like that that is required for silkspawners. I instantiate them with the fake world. **Again I can't use on load complete or spawners will try and load after jei and other mods doing it and not show up in the tab.** 

Why isn't sounds on client tick or something like that? My world doesn't tick and yet it plays sounds before the main menu even opens? Nothing from my code ticks for entity cache so this isn't caused on my side.

 Other mods do this method as well like nei(1.5.2-1.7.10),menu mobs(only if it selects your entity since it's re-written from bpkrscore).

**Comment by darthvader45** [comment]
Same exact crash happens when I have Gegy's Statue mod installed alongside it, so it could be a compat issue.

**Comment by jredfox** [comment]
I found out the cause of the crash. https://github.com/gegy1000/JurassiCraft2/blob/master-1.12.2/src/main/java/org/jurassicraft/client/sound/EntitySound.java#L33 which is having a null point exception due to the player being null in post init.

this seems to be on your side I don't know why it's even trying to play the entity's sound I just created the entity and that was it. My fake world class also doesn't tick

**Comment by jredfox** [comment]
it seems to crash without evil notch lib and any of my mods just jc and latest llib

**Comment by jredfox** [comment]
confirmed also same crash with the statue mod

**Comment by PT400C** [comment]
@jredfox This should work after JurassiCraft-1.12.2-2.1.21.

**Comment by darthvader45** [comment]
Thank you, now I can finally have my John Hammond statue in the Innovation
Center.

**Comment by PT400C** [comment]
_Uh, that was an instant-reply :O_

**Comment by jredfox** [comment]
issue still happens with latest jurassicraft JurassiCraft-1.12.2-2.1.20

**Comment by PT400C** [comment]
.... please read my post properly. I said 1.12.2-2.1.2**1** not 1.12.2-2.1.2**0**.

**Comment by jredfox** [comment]
so upload the patch otherwise this issue remains open

**Comment by PT400C** [comment]
The patch is going to be released sometime near in the future. It's going to stay closed as long as it seems that the issue was resolved.
