### ISSUE TITLE
Server Memory Crash after killing dino and corpse

### ISSUE THREAD

**Issue by memykil** [JurassiCraftTeam/JurassiCraft2#500]
JurassiCraft-1.12.2-2.1.18 and llibrary-1.7.15-1.12.2
After killing a dino and corpse the memory exceeded the allocated 6 gig causing the server to continuously reboot. I removed the 2 mods and re added them and the server started fine. JCraft is a major feature for this server. Any help would be much appreciated.
Memory Dump
https://pastebin.com/Vs7yTWhG

**Comment by PT400C** [comment]
This is a known bug and will be fixed with the upcoming release. ~Closed
