### ISSUE TITLE
[Suggestion] Hammond Statue

### ISSUE THREAD

**Issue by darthvader45** [JurassiCraftTeam/JurassiCraft2#511]
I would love to see the Hammond Statue from Jurassic World make it into the mod, and as such have prepared a textured model ready to be used.  Texture and model are linked here: https://www.dropbox.com/s/tpjmzqj51poywex/hammond_statue.zip?dl=1

**Comment by Cazsius** [comment]
Please add suggestions to the discord channel linked below:
https://discord.gg/VkXWtPD
