### ISSUE TITLE
Crash  Unexpected error java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Njet75** [JurassiCraftTeam/JurassiCraft2#512]
Get this crash with latest version JurassiCraft-1.12.2-2.1.19.jar.

Hope the crashlog helps

/Michael
[crash-2018-12-30_00.37.00-client.txt](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2716842/crash-2018-12-30_00.37.00-client.txt)

**Comment by PT400C** [comment]
@Njet75 Does that happen all the time or did it happen just once?

**Comment by Njet75** [comment]
Thanks for Quick answer.
Its happen two times and seems to be sporadic.
One time I teleported to a Place and the other time i did nothing.
The area of the map should not have any Jurassicraft content chunkloaded. 

/ Michael

**Comment by PT400C** [comment]
Thank you very much for that report. We'll try to fix this issue in the future.

**Comment by PT400C** [comment]
This should not happen again with JurassiCraft 1.12.2-2.1.20.
