### ISSUE TITLE
Tyrannosaurus Rex Animation bug and AI issue

### ISSUE THREAD

**Issue by ImaStego** [JurassiCraftTeam/JurassiCraft2#515]
I've found out that the Tyrannosaurus Rex swims (Swimming Animation). activates in 1 block deep of water (or 2).
![image](https://user-images.githubusercontent.com/46329503/50610549-5cbe2700-0ea1-11e9-9645-fbd139e253c4.png) (Sorry if the screenshot is hard to see but u should try it for yourself as well as The Tyrannosaurus Rex killing). 

Second problem:
I don't know if this was intentional or not but Tyrannosaurus Rex does not kill each other when there is more than two Rexes in the area.

**Comment by PT400C** [comment]
The first point will be fixed in the next release, the second one still needs verification.

**Comment by PT400C** [comment]
@ImaStego When I tried it, four+ Rexes attack eachother until one is dead.
