### ISSUE TITLE
BlockVine Causing Crash on SpongeForge Servers

### ISSUE THREAD

**Issue by system-operator** [JurassiCraftTeam/JurassiCraft2#522]
https://github.com/JurassiCraftTeam/JurassiCraft2/blob/fd9fa57e4c7f96aad8c6f68f18d1bd249883f122/src/main/java/org/jurassicraft/server/util/JCBlockVine.java

**JC Version:** JurassiCraft-1.12.2-2.1.19
**SpongeForge:** 1.12.2-2768-7.1.5-RC3515
**Crash Report:** https://hastebin.com/biwusoxini.rb

Searching my server pack for "BlockVine" reveals your mod as the culprit:
```
Binary file mods/JurassiCraft-1.12.2-2.1.19.jar matches
Binary file mods/_aspongeforge-1.12.2-2768-7.1.5-RC3515.jar matches
```

Please advise! Removed for now, thank you!

**Comment by PT400C** [comment]
We can't reproduce that issue. ~closed
