### ISSUE TITLE
Missing Vine texture

### ISSUE THREAD

**Issue by Zyene** [JurassiCraftTeam/JurassiCraft2#523]
Whenever I add the mod the Vines becomes a missing block/texture, also it's not generating properly.
The Vines were normal if it was placed though.
![2019-01-17_16 19 18](https://user-images.githubusercontent.com/46776896/51305673-87e67000-1a76-11e9-90cd-f3a07990c04b.png)
![2019-01-17_16 18 37](https://user-images.githubusercontent.com/46776896/51305694-8fa61480-1a76-11e9-9358-494226b48892.png)
![2019-01-17_16 18 50](https://user-images.githubusercontent.com/46776896/51305695-903eab00-1a76-11e9-8778-781f5c435e63.png)
![2019-01-17_16 27 10](https://user-images.githubusercontent.com/46776896/51305698-92a10500-1a76-11e9-893e-084669fd8ebf.png)

Also I'm not using a texture pack.

**Comment by PT400C** [comment]
@Zyene Are you using the liteloader together with Forge? If so, JurassiCraft isn't compatible with the liteloader in general. If you're not using it, then please send your full mod list so that we could track down the issue.

**Comment by Zyene** [comment]
I see so it was the Liteloader. thanks!

**Comment by PT400C** [comment]
Oh, alright. We're trying to resolve that incompatibility with the liteloader but as the developer seems to be inactive, we can't do much so far. #486
