### ISSUE TITLE
crash while loading mods

### ISSUE THREAD

**Issue by mr2meowsYT** [JurassiCraftTeam/JurassiCraft2#524]
There was a severe problem during mod loading that has caused the game to fail

(it says it caught exception from jurrasicraft

**Comment by PT400C** [comment]
@mr2meowsYT Could you send your crash log so that we can track down the issue?

**Comment by mr2meowsYT** [comment]
@PT400C how do i retrive it after i close the launcher

**Comment by PT400C** [comment]
Go into the .minecraft/logs folder. There should be a latest.log file.

**Comment by mr2meowsYT** [comment]
thar are mutiple 1/22/2019 logssssssss

**Comment by PT400C** [comment]
But there should be a latest.log file.

**Comment by PT400C** [comment]
I see, but that doesn't always mean that JurassiCraft is the cause of the crash. Please just do that what I suggested above. That always points out the real cause at the end.

**Comment by mr2meowsYT** [comment]
wat are teh known causes of issues with jurrasicraft

**Comment by PT400C** [comment]
Currently there are only two known cases of JurassiCraft causing crashes with other mods. These are Statues mod by Gegy1000 and EvilNotchLib.

**Comment by mr2meowsYT** [comment]
im gonna try to use jurrasicraft again

**Comment by mr2meowsYT** [comment]
if it crashes i will upload the log (if it does not i will say it and close this)

**Comment by mr2meowsYT** [comment]
i have like 101+ mods so it will take a min to load

**Comment by mr2meowsYT** [comment]
[latest.log](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2799430/latest.log)
crashhhhhhhhhhhh log 👍 :)

**Comment by PT400C** [comment]
Do you have this mod installed: https://minecraft.curseforge.com/projects/fexcraft-common-library?

**Comment by mr2meowsYT** [comment]
@PT400C yee

**Comment by PT400C** [comment]
Could you try removing that one for now?

**Comment by mr2meowsYT** [comment]
ok i remove fex carszzzzz

**Comment by mr2meowsYT** [comment]
me use flans mod for fex carsz (flans mod has fex cars addon for itself)

**Comment by mr2meowsYT** [comment]
use rift 1.13 mod api if u want to make jurassicraft on 1.13

**Comment by mr2meowsYT** [comment]
ISSUE FIXED
