### ISSUE TITLE
Tyrannosaurus Spawn Crash

### ISSUE THREAD

**Issue by GarchompGirl** [JurassiCraftTeam/JurassiCraft2#533]
I was playing with my friend on my server with this mod and some other mods and when I spawned a Tyrannosaurus, My game was frozen for like about 2-3 minutes then MC closed. I can fix most MC crashes myself but this is very annoying due to me and my friend wanting to make a Dinosaur Park.

https://pastebin.com/raw/95ubqXGX

**Comment by PT400C** [comment]
By looking into the log I guess that you use the latest JurassiCraft version, right? Also, could you send me a file with all the mods you have active (in form of a zip). As it currently seems, it's an incompatibility with one of the other mods which you've got installed.

**Comment by GarchompGirl** [comment]
https://www.dropbox.com/s/kyt80ri4eomu576/mods.zip?dl=1
Theres the mods.
https://mclo.gs/0WNfB95
Theres the server console
And yes it is the latest Jurassicraft.

**Comment by PT400C** [comment]
Verified. I'll investigate that now. Thank you very much for the report!

**Comment by PT400C** [comment]
So, as a first information: It's the MorePlayerModels mod which causes the problem.

**Comment by PT400C** [comment]
@GarchompGirl This version of JurassiCraft should work. Please send your feedback :)
[fix.zip](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2816292/fix.zip)

**Comment by GarchompGirl** [comment]
Ok I figured it out, When you spawn a Custom NPC and spawn a Dinosaur minecraft freezes and becomes inresponsive.

**Comment by PT400C** [comment]
@GarchompGirl Does that still happen with the fix I sent?
