### ISSUE TITLE
DNA Combinator-Hybridizer Combines different species

### ISSUE THREAD

**Issue by memykil** [JurassiCraftTeam/JurassiCraft2#534]
Iactor here. I was told this is a bug. You can combine different species of plants or dinosaurs to get a 100 disc. You can't mix plants and dinos. Say you had a 60% rex you can combine it with a 40% dilo to get 100% rex. Or a 30 rex and a 25 brach to get 55 rex. Then you could combine the 55 rex with a 45 muss to get a 100 rex. It always has to be lower for the one you are combining into the one you want.

**Comment by GarchompGirl** [comment]
I experienced this glitch too on my aternos server a long time ago when me and my friends were playing Jurassicraft survival.
