### ISSUE TITLE
Dig site chest can contain invalid items

### ISSUE THREAD

**Issue by HariboTer** [JurassiCraftTeam/JurassiCraft2#536]
I found a textureless item called a "Velociraptor First Dorsal Fin" in a dig site chest (playing with the newest version on curseforge, 2.1.20). It does not seem to be intentional^^
![grafik](https://user-images.githubusercontent.com/3805624/51999271-a444cc80-24ba-11e9-85cd-cb888b8916e3.png)

**Comment by PT400C** [comment]
Verified. I'll investigate that now.
