### ISSUE TITLE
[Suggestion] Add more cars to the mod

### ISSUE THREAD

**Issue by jhonny909011** [JurassiCraftTeam/JurassiCraft2#550]
I loved your mod even more the cars you can make a pack of cars please

**Comment by jhonny909011** [comment]
use these cars from the movie jurassic world
https://jurassicpark.fandom.com/wiki/Category:Jurassic_World_(park)_vehicles

**Comment by Cazsius** [comment]
Please add suggestions to the discord channel linked below:
https://discord.gg/VkXWtPD
