### ISSUE TITLE
Raptor glitching in walls

### ISSUE THREAD

**Issue by charlielegoman** [JurassiCraftTeam/JurassiCraft2#554]
Really big Female raptors go in walls slightly and take damage. This has only happened with really big raptors on the jc server. I haven't tested it with male raptors yet. This glitch has happened to me 3 times and all raptors have died to this glitch. Hope this helps. Ps Goth the moderator was at the scene.

**Comment by PT400C** [comment]
Thanks for reporting this glitch, although it's already known to the team (#411).
