### ISSUE TITLE
Vines missing Item texture

### ISSUE THREAD

**Issue by EntityENN** [JurassiCraftTeam/JurassiCraft2#555]
The texture for vines is missing whenever the mod is enabled onto the game and seems to have been missing from at least 5 versions of the mod up till the current version and the vines don't generate on they're own when generating a world but they can be manually placed down and look just fine.

**Comment by PT400C** [comment]
@EntityENN Hey, do you use the Liteloader and/or BOP with JurassiCraft? If not, please send a full list of your mods.
Quick reference: As far as we know, the Liteloader is dead and won't be supported by JC anymore. And BOP is still incompatible - this may change in the future.

**Comment by EntityENN** [comment]
Well I used liteloader so I'll take that as maybe the problem?

**Comment by PT400C** [comment]
Exactly. JC doesn't work with the liteloader. You could try removing it. That should resolve the issue.

**Comment by EntityENN** [comment]
Alright, I'll try that, also I wasn't sure on where to ask this or if it
had been answered already somewhere but I was wondering if the other
creatures from the mod before 2.0 are gonna be added back over time or not.
Im just curious if it's planned or not.

**Comment by PT400C** [comment]
It's planned that they get readded, yes. But of cause after a mayor overhaul.

**Comment by EntityENN** [comment]
Alright cool.
