### ISSUE TITLE
None Placeable Eggs

### ISSUE THREAD

**Issue by ottotrainer445092** [JurassiCraftTeam/JurassiCraft2#556]
When I'm in creative and I get an egg I can't place it. I tried in survival to test, yet still couldn't. The eggs were just not working. If you know a fix please tell me. -Newest Version

**Comment by PT400C** [comment]
@ottotrainer445092 Did you incubate the eggs to be hatched eggs?

**Comment by ottotrainer445092** [comment]
> @ottotrainer445092 Did you incubate the eggs to be hatched eggs?

**Comment by ottotrainer445092** [comment]
I couldn't place the eggs in the incubator.
