### ISSUE TITLE
1.8.9 doesnt work

### ISSUE THREAD

**Issue by Tjbillick** [JurassiCraftTeam/JurassiCraft2#558]
I cant get mc to work with this version for some reason and its only only version with more than like 6 dinos

**Comment by PT400C** [comment]
1.8.9 is no longer supported. Please update to 1.12.2. That version contains 10 dinosaurs.

**Comment by Tjbillick** [comment]
I understand if its to difficult but why are there only 10 dinosaurs in
jurassic craft. Many people loved 1.8 because of so many dinosaurs because
like me we are building our own jurassic parks. Id be nice to see more
dinosaurs from the newer movies like carnotaurus,stigy,etc.
One more thing can you guys add the raptor name tag thing back. Me and my
sister were disappointed that we couldn't turn our raptor into blue. Sorry
for such a long rant.

**Comment by PT400C** [comment]
You could visit our Discord and ask why JC changed after 1.8 there. That's a better place than GitHub.

Also there, you could suggest to add the nametag feature. https://discord.gg/pha43NH

**Comment by Tjbillick** [comment]
Ok thank you
