### ISSUE TITLE
Skeletons won't craft

### ISSUE THREAD

**Issue by Canus8** [JurassiCraftTeam/JurassiCraft2#562]
I have fresh bones from velociraptors that I want to craft into a skeleton.  The wiki states that the following arrangement of the bones on the Skeleton Assembly Table makes a raptor skeleton:
![Screenshot (491)](https://user-images.githubusercontent.com/49524173/56066651-6d0a5b80-5d46-11e9-993c-68c9c895848a.png)

However, when I used it in-game, it didn't give me anything:
![Screenshot (521)](https://user-images.githubusercontent.com/49524173/56066674-83b0b280-5d46-11e9-8744-2a1823aaf256.png)

I think I had also tried with Mussaurus, with the same issue.  I know that Parasaurolophus and Dilophosaurus work just fine, but these others don't for some reason.

**Comment by Canus8** [comment]
I also am making sure in my attempt that all the bones contain the same genome, so that is not the issue here.

**Comment by Brotatsun64** [comment]
I work for the mod, that recipe is broken

**Comment by Canus8** [comment]
man...  I was wanting a raptor skeleton.  Is it a different arrangement or is it completely un-craftable?

**Comment by Brotatsun64** [comment]
different arrangement

**Comment by Canus8** [comment]
Could you see about fixing the wiki?  I don't have a wikia account, so I couldn't fix it for everyone else if you just told me.

The skeletons look amazing, by the way.

**Comment by Brotatsun64** [comment]
i mean we don't run the wiki, but you can just kinda figure out the recipe since in that one it had the tail in front of the head

**Comment by Brotatsun64** [comment]
you could try using JEI until the wiki is fixed, we suggest using that anyways

**Comment by Canus8** [comment]
JEI?

**Comment by Brotatsun64** [comment]
Just enough items, it shows recipes of things and is jc compatible

**Comment by Canus8** [comment]
hmm.  I don't want too many mods, as I am also using Fossils and Archeology.  I will try again once I replace the hip bone.  I dropped it, and while I was here, it apparently de-spawned.  I will likely post screenshots of all the REAL recipes once I get them.  Again, the Dilo and Para work like the wiki states right now.

Also, can we be able to place skulls of other dinosaurs in the future, the way we can with T. rex right now?

I don't feel like adding a suggestion post that would just be deleted.

**Comment by Canus8** [comment]
Alright, I can't find it. (and I am not going to try remembering 1 out of 50 possible combinations).  Could you tell me/show me the recipe?

**Comment by Brotatsun64** [comment]
JEI, idk the recipe by heart

**Comment by Canus8** [comment]
how do you install it after downloading it?  It isn't a forge mod...

**Comment by Brotatsun64** [comment]
i mean you install it like any other mod

**Comment by Canus8** [comment]
oh

**Comment by PT400C** [comment]
@Canus8 Is this issue resolved? And for reference: We don't create that wiki you screenshotted and it might be out of date.

**Comment by Canus8** [comment]
I guess it is resolved.  I guess you can't believe anything on the internet :/
