### ISSUE TITLE
Dinosaurs spawn when dino spawning is off

### ISSUE THREAD

**Issue by Canus8** [JurassiCraftTeam/JurassiCraft2#567]
I was trying to clear out the first natural-spawn dinosaurs from my world - a large flock of lagimimus in a desert, when I noticed some, and a few lagoceratops, in a savanah.  I know I had been past that savanah before, and there were some gallimimus that had spawned in there, so I just started clearing it out, assuming that the desert gallimimus would just starve to death.  As I kept going deeper into the savanah, more and more gallimimus appeared, and I kept working on removing them.  Many of the chunks that were loaded with gallimimus in this savanah were chunks that, i am pretty sure, had never been loaded before.  I also have, due to the lag they cause, disabled dinosaur spawning, and dino carcasses.  However, both appear to still be on.
![Screenshot (535)](https://user-images.githubusercontent.com/49524173/56366304-d4019780-61c0-11e9-8b2d-d1db436de814.png)
![Screenshot (536)](https://user-images.githubusercontent.com/49524173/56366306-d4019780-61c0-11e9-8a47-7223f1b69e8f.png)

Can someone else confirm that this is a bug?  I can't stand the lag the naturally-spawning dinosaurs cause.

**Comment by Canus8** [comment]
I have thought about making a wither just so that it can kill the dinosaurs that have spawned naturally.

**Comment by PT400C** [comment]
Hey,

did you try restarting your game? There might be issues when switching the
natural spawning on and off without a reboot.

Canus8 <notifications@github.com> schrieb am Do., 18. Apr. 2019, 16:06:

**Comment by Canus8** [comment]
I loaded these gallimimus nearly a month ago.  I have had dino spawning off for days, as well.

**Comment by Canus8** [comment]
at least a week, in fact

**Comment by PT400C** [comment]
@Canus8 That's actually impossible. It's most likely that they spawned before.

**Comment by Canus8** [comment]
I am certain that I have not been to many of the places they have spawned.  I also saw Mussaurus, which they, along with triceratops, I did not encounter in the wild until the second time I turned dino spawning on, and was in a completely different part of the world.

**Comment by Canus8** [comment]
Unless it spawns them per biome loaded, and just having a single chunk of savanah will spawn them throughout that entire savanah.  But I don't think that is a thing, or possible.

**Comment by PT400C** [comment]
@Canus8 We received some feedback from other users which support your statements. So, does it still happen? Were you on a server or client world? Were it always galimimi? Which other mods do you use? Could you send your jurassicraft.cfg file?

**Comment by Canus8** [comment]
I use single player, if that means anything.  There were newly spawned Galimimus, as well as Mussaurus, Triceratops, and even a T rex.  Most of them are Gallies, though.

**Comment by PT400C** [comment]
@Canus8 Which mods do you have installed in total when this happens? (I think that it might be an incompatibility)

**Comment by PT400C** [comment]
@Canus8 A little bit of investigation lead to the solution that CustomMobSpawner might be the cause. In case you want to not have JurassiCraft dinosaurs spawning, you actually have to disable that in the configs of CustomMobSpawner. If you don't use that mod and they still spawn, feel free to answer again :)
