### ISSUE TITLE
I would like a new version

### ISSUE THREAD

**Issue by nn26bn** [JurassiCraftTeam/JurassiCraft2#568]
hi, 
I hope you could translate this message: (it's in frensh)
Je joue depuis un moment avec Jurassic craft et pour moi dans les dernières versions il manque des espèces parce qu'on fait vite le tour des 10 dinosaures. le dinopad manque aussi c’était quelque chose de super !!! 🦖 Je suis en train de me lasser de ce mode donc vite il y a urgence parce que je trouve le principe super !!! Je voulais aussi vous féliciter car vous avez quand même crée le meilleur mode de minecraft et vous avez apporter quelque choses d’incroyable à celui ci. je changerai uniquement ça dans ce mode quand même complet . La manière de crée les dinosaures est sympas. Il n'y a rien a changer dans ce mode mise a part les 2 point énonce au paravent.
Think you so much and I hope Jurassic craft is going to chnage 😜😜😜

**Comment by Gamebrothers4** [comment]
Jc will add dinosaurs more dinosaurs in the future.

**Comment by PT400C** [comment]
@nn26bn We appreciate your feedback. But if you want to receive further information concerning planned updates and features, you may visit our Discord :) URL: https://discord.gg/RBR6XZj
