### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by manorei18** [JurassiCraftTeam/JurassiCraft2#580]
Hello, I'm reporting a bug you're having in your mod. when I'm going to break one of the fossils when it's time to mine, nothing comes out, the fossils I'm only able to get in the creative mode but not survive when I break the fossil block hoping to drop a fossil, I do not drop anything. the version I'm playing from your mod and 21.12. please settle. appreciate

**Comment by PT400C** [comment]
In order to get the actual fossils, you have to use "Plaster and Bandage"
on the blocks. This recovers the instable fossils and you get an encased
fossil block. This one can be mined with any pickaxe stronger than iron.

manorei18 <notifications@github.com> schrieb am Mo., 17. Juni 2019, 19:04:

**Comment by PT400C** [comment]
@manorei18 I will close this now.
